/**
 * The password-reset pages **as `Django==2.2.27` rendered them**, captured by running v1's own
 * templates inside the v1 image (`fondo-v1:parity`) against `api.settings.production` with
 * `HOST_URL_APP=http://localhost:3000`.
 *
 * The only substitution is the CSRF token, replaced by 64 `A`s so the strings are stable.
 *
 * ⚠️ These are the reference, not the implementation's own output. If a template edit changes
 * one byte of whitespace — Django leaves a lot of it behind where `{% block %}`, `{% load %}`
 * and `{% if %}` tags used to be — the spec that compares against these fails.
 */

/** The stand-in for the 64-character masked CSRF token. */
export const FIXED_CSRF_TOKEN = 'A'.repeat(64);

export const V1_FORM =
  '<!DOCTYPE html>\n<html>\n\n<head>\n\t<title>Fondo Monta\u00f1ez</title>\n\t<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">\n\t\n\t<link rel="stylesheet" type="text/css" href="/static/style.css">\n\t<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">\n\t<script>\n\t\tfunction onSubmit() {\n\t\t\tdocument.getElementById(\'submit_button\').disabled = true\n\t\t}\n\t</script>\n</head>\n\n<body>\n\t\n\t<div class="container">\n\t\t<center><img class="card-img-top banner" src="/static/banner.png"></center>\n\t\t<form onsubmit="onSubmit()" method="post" class="form">\n\t\t\t<center><h2>Recuperaci\u00f3n de contrase\u00f1a</h2></center>\n\t\t\t<input type="hidden" name="csrfmiddlewaretoken" value="AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA">\n\t\t\t<!-- <p><label for="id_email">Email:</label> <input type="email" name="email" maxlength="254" required id="id_email"></p> -->\n\t\t\t<div class="form-group">\n\t\t\t\t<input type="email" class="form-control" id="id_email" name="email" required placeholder="Email" maxlength="254">\n\t\t\t</div>\n\t\t\t<button class="btn btn-danger btn-lg btn-block" id="submit_button" type="submit">Enviar</button>\n\t\t</form>\n\t</div>\n\t\n</body>\n\n</html>';

export const V1_DONE =
  '<!DOCTYPE html>\n<html>\n\n<head>\n    <title>Fondo Monta\u00f1ez</title>\n    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">\n\t\n\t<link rel="stylesheet" type="text/css" href="/static/style.css">\n\t<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">\n</head>\n\n<body>\n\t\n\t<div class="form">\n\t\t<div class="alert alert-success">\n\t\t\t<center><h2>ENVIADO</h2></center>\n\t\t\t<p>\n\t\t\t\tSi una cuenta existe con la direcci\u00f3n de correo ingresada, se te enviar\u00e1 un email con las instrucciones para restaurar tu contrase\u00f1a.\n\t\t\t\tDeber\u00edas recibirlo pronto.\n\t\t\t</p>\n\t\t\t<p>\n\t\t\t\tSi no recibes el email, favor aseg\u00farate de que la direcci\u00f3n de correo que has ingresado sea la misma registrada en la aplicaci\u00f3n. Por otro lado, revisa la carpeta de spam.\n\t\t\t</p>\n\t\t</div>\n\t</div>\n\t\n</body>\n\n</html>';

export const V1_COMPLETE =
  '<!DOCTYPE html>\n<html>\n\n<head>\n    <title>Fondo Monta\u00f1ez</title>\n    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">\n\t\n\t<link rel="stylesheet" type="text/css" href="/static/style.css">\n\t<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">\n</head>\n\n<body>\n\t\n\t\t<div class="form">\n            <div class="alert alert-success">\n                <center><h2>Cambio de contrase\u00f1a exitoso</h2></center>\n\t\t\t  \t<center>\n\t\t\t  \t\t<p>Tu contrase\u00f1a ha sido actualizada.</p>\n\t\t\t  \t\t<a href="http://localhost:3000">Ir a p\u00e1gina principal</a>\n\t\t\t  \t</center>\n\t\t\t</div>\n\t\t</div>\n\t\n</body>\n\n</html>';

export const V1_CONFIRM_VALID =
  '<!DOCTYPE html>\n<html>\n\n<head>\n    <title>Fondo Monta\u00f1ez</title>\n    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">\n\t\n\t<link rel="stylesheet" type="text/css" href="/static/style.css">\n\t<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">\n</head>\n\n<body>\n    \n    <div class="container">\n        <center><img class="card-img-top banner" src="/static/banner.png"></center>\n        \n            <form method="post" class="form">\n                <center><h2>Cambio de contrase\u00f1a</h2></center>\n                \n\n                <input type="hidden" name="csrfmiddlewaretoken" value="AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA">\n                <div class="form-group">\n                    <input type="password" class="form-control" id="id_new_password1" name="new_password1" required placeholder="Nueva contrase\u00f1a">\n                </div>\n                <div class="form-group">\n                    <input type="password" class="form-control" id="id_new_password2" name="new_password2" required placeholder="Confirmaci\u00f3n de nueva contrase\u00f1a">\n                </div>\n                <button class="btn btn-danger btn-lg btn-block" type="submit">Cambiar contrase\u00f1a</button>\n            </form>\n        \n    </div>\n    \n</body>\n\n</html>\n';

export const V1_CONFIRM_INVALID =
  '<!DOCTYPE html>\n<html>\n\n<head>\n    <title>Fondo Monta\u00f1ez</title>\n    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">\n\t\n\t<link rel="stylesheet" type="text/css" href="/static/style.css">\n\t<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">\n</head>\n\n<body>\n    \n    <div class="container">\n        <center><img class="card-img-top banner" src="/static/banner.png"></center>\n        \n            <div class="form">\n                <div class="alert alert-danger">\n                    <p>\n                        El enlace de restauraci\u00f3n de contrase\u00f1a es inv\u00e1lido, posiblemente porque ya ha sido usado.\n                        Favor enviar una nueva solicitud de restauraci\u00f3n de contrase\u00f1a.\n                    </p>\n                </div>\n            </div>\n        \n    </div>\n    \n</body>\n\n</html>\n';

export const V1_CONFIRM_MISMATCH =
  '<!DOCTYPE html>\n<html>\n\n<head>\n    <title>Fondo Monta\u00f1ez</title>\n    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">\n\t\n\t<link rel="stylesheet" type="text/css" href="/static/style.css">\n\t<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">\n</head>\n\n<body>\n    \n    <div class="container">\n        <center><img class="card-img-top banner" src="/static/banner.png"></center>\n        \n            <form method="post" class="form">\n                <center><h2>Cambio de contrase\u00f1a</h2></center>\n                \n                    \n                        \n                    \n                        \n                            <div class="alert alert-danger"><ul class="errorlist"><li>The two password fields didn&#39;t match.</li></ul></div>\n                        \n                    \n                \n\n                <input type="hidden" name="csrfmiddlewaretoken" value="AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA">\n                <div class="form-group">\n                    <input type="password" class="form-control" id="id_new_password1" name="new_password1" required placeholder="Nueva contrase\u00f1a">\n                </div>\n                <div class="form-group">\n                    <input type="password" class="form-control" id="id_new_password2" name="new_password2" required placeholder="Confirmaci\u00f3n de nueva contrase\u00f1a">\n                </div>\n                <button class="btn btn-danger btn-lg btn-block" type="submit">Cambiar contrase\u00f1a</button>\n            </form>\n        \n    </div>\n    \n</body>\n\n</html>\n';

export const V1_CONFIRM_NUMERIC =
  '<!DOCTYPE html>\n<html>\n\n<head>\n    <title>Fondo Monta\u00f1ez</title>\n    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">\n\t\n\t<link rel="stylesheet" type="text/css" href="/static/style.css">\n\t<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">\n</head>\n\n<body>\n    \n    <div class="container">\n        <center><img class="card-img-top banner" src="/static/banner.png"></center>\n        \n            <form method="post" class="form">\n                <center><h2>Cambio de contrase\u00f1a</h2></center>\n                \n                    \n                        \n                    \n                        \n                            <div class="alert alert-danger"><ul class="errorlist"><li>This password is entirely numeric.</li></ul></div>\n                        \n                    \n                \n\n                <input type="hidden" name="csrfmiddlewaretoken" value="AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA">\n                <div class="form-group">\n                    <input type="password" class="form-control" id="id_new_password1" name="new_password1" required placeholder="Nueva contrase\u00f1a">\n                </div>\n                <div class="form-group">\n                    <input type="password" class="form-control" id="id_new_password2" name="new_password2" required placeholder="Confirmaci\u00f3n de nueva contrase\u00f1a">\n                </div>\n                <button class="btn btn-danger btn-lg btn-block" type="submit">Cambiar contrase\u00f1a</button>\n            </form>\n        \n    </div>\n    \n</body>\n\n</html>\n';

export const V1_CSRF_FAILURE_NO_COOKIE =
  '\n<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta http-equiv="content-type" content="text/html; charset=utf-8">\n  <meta name="robots" content="NONE,NOARCHIVE">\n  <title>403 Forbidden</title>\n  <style type="text/css">\n    html * { padding:0; margin:0; }\n    body * { padding:10px 20px; }\n    body * * { padding:0; }\n    body { font:small sans-serif; background:#eee; color:#000; }\n    body>div { border-bottom:1px solid #ddd; }\n    h1 { font-weight:normal; margin-bottom:.4em; }\n    h1 span { font-size:60%; color:#666; font-weight:normal; }\n    #info { background:#f6f6f6; }\n    #info ul { margin: 0.5em 4em; }\n    #info p, #summary p { padding-top:10px; }\n    #summary { background: #ffc; }\n    #explanation { background:#eee; border-bottom: 0px none; }\n  </style>\n</head>\n<body>\n<div id="summary">\n  <h1>Forbidden <span>(403)</span></h1>\n  <p>CSRF verification failed. Request aborted.</p>\n\n\n  <p>You are seeing this message because this site requires a CSRF cookie when submitting forms. This cookie is required for security reasons, to ensure that your browser is not being hijacked by third parties.</p>\n  <p>If you have configured your browser to disable cookies, please re-enable them, at least for this site, or for &#39;same-origin&#39; requests.</p>\n\n</div>\n\n<div id="explanation">\n  <p><small>More information is available with DEBUG=True.</small></p>\n</div>\n\n</body>\n</html>\n';

export const V1_CSRF_FAILURE_BAD_TOKEN =
  '\n<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta http-equiv="content-type" content="text/html; charset=utf-8">\n  <meta name="robots" content="NONE,NOARCHIVE">\n  <title>403 Forbidden</title>\n  <style type="text/css">\n    html * { padding:0; margin:0; }\n    body * { padding:10px 20px; }\n    body * * { padding:0; }\n    body { font:small sans-serif; background:#eee; color:#000; }\n    body>div { border-bottom:1px solid #ddd; }\n    h1 { font-weight:normal; margin-bottom:.4em; }\n    h1 span { font-size:60%; color:#666; font-weight:normal; }\n    #info { background:#f6f6f6; }\n    #info ul { margin: 0.5em 4em; }\n    #info p, #summary p { padding-top:10px; }\n    #summary { background: #ffc; }\n    #explanation { background:#eee; border-bottom: 0px none; }\n  </style>\n</head>\n<body>\n<div id="summary">\n  <h1>Forbidden <span>(403)</span></h1>\n  <p>CSRF verification failed. Request aborted.</p>\n\n\n</div>\n\n<div id="explanation">\n  <p><small>More information is available with DEBUG=True.</small></p>\n</div>\n\n</body>\n</html>\n';
