/**
 * **Captured from the running v1 stack against the live `fondodev` fixture**, not written by
 * hand and not derived from v2's implementation.
 *
 * Produced by rendering `LoanSerializer` / `LoanDetailSerializer` (`fondo_api/serializers.py:73-110`)
 * over real rows inside the v1 container (`Django==2.2.27` / `djangorestframework` /
 * `Babel==2.9.1`, `LANGUAGE_LOCALE='es'`) and dumping `serializer.data` as JSON. Each entry
 * carries the `raw` column values it was built from, so `loan.serializers.spec.ts` can feed
 * exactly those to v2 and compare the whole object.
 *
 * ## The row that pays for this file
 *
 * Loan **1** has `created_at = 2018-01-01T00:00:00+00:00` and v1 renders it as
 * **`31 dic. 2017`** — `timezone.localtime()` first (`serializers.py:88-90`), so a UTC instant
 * just after midnight is the *previous* Bogotá day. Its `disbursement_date`, a `DateField`, is
 * rendered with **no** conversion. That is plan rule **5c** as a live row rather than as a
 * warning: reading `created_at` with `fromDateColumn` would print `1 ene. 2018` here and would
 * be wrong for roughly 21% of every day, in CI-green code.
 *
 * ⚠️ **`rate` is a JSON string**, not a number — `COERCE_DECIMAL_TO_STRING` defaults to `True`
 * and v1 does not override it. `user_id` is a plain integer. `keys` records DRF's
 * `Meta.fields` ordering, which `JSONRenderer` preserves and does not sort.
 *
 * ⚠️ **Do not edit these to make a test pass.** They are the specification.
 */
export interface LoanSerializerFixture {
  readonly keys: readonly string[];
  readonly data: Record<string, unknown>;
  readonly raw: {
    readonly id: number;
    readonly value: number;
    readonly timelimit: number;
    readonly disbursement_date: string;
    readonly payment: number;
    readonly created_at: string;
    readonly fee: number;
    readonly comments: string | null;
    readonly state: number;
    readonly rate: string;
    readonly user_id: number;
    readonly prev_loan_id: number | null;
    readonly refinanced_loan: number | null;
    readonly disbursement_value: number | null;
    readonly first_name: string;
    readonly last_name: string;
  };
}

export interface LoanDetailSerializerFixture {
  readonly keys: readonly string[];
  readonly data: Record<string, unknown>;
  readonly raw: {
    readonly minimum_payment: number;
    readonly total_payment: number;
    readonly payday_limit: string;
    readonly interests: number;
    readonly capital_balance: number;
    readonly from_date: string;
  };
}

export const V1_LOAN_SERIALIZER_FIXTURES: readonly LoanSerializerFixture[] = Object.freeze([
  {
    keys: [
      'value',
      'timelimit',
      'disbursement_date',
      'payment',
      'created_at',
      'fee',
      'comments',
      'state',
      'user_full_name',
      'id',
      'rate',
      'is_refinanced',
      'refinanced_loan',
      'user_id',
      'disbursement_value',
    ],
    data: {
      value: 1644721,
      timelimit: 12,
      disbursement_date: '20 feb. 2017',
      payment: 1,
      created_at: '31 dic. 2017',
      fee: 1,
      comments: 'Refinanciación',
      state: 3,
      user_full_name: 'N@CHO Montañez Herrera',
      id: 1,
      rate: '0.025',
      is_refinanced: false,
      refinanced_loan: null,
      user_id: 5,
      disbursement_value: null,
    },
    raw: {
      id: 1,
      value: 1644721,
      timelimit: 12,
      disbursement_date: '2017-02-20',
      payment: 1,
      created_at: '2018-01-01T00:00:00+00:00',
      fee: 1,
      comments: 'Refinanciación',
      state: 3,
      rate: '0.025',
      user_id: 5,
      prev_loan_id: null,
      refinanced_loan: null,
      disbursement_value: null,
      first_name: 'N@CHO',
      last_name: 'Montañez Herrera',
    },
  },
  {
    keys: [
      'value',
      'timelimit',
      'disbursement_date',
      'payment',
      'created_at',
      'fee',
      'comments',
      'state',
      'user_full_name',
      'id',
      'rate',
      'is_refinanced',
      'refinanced_loan',
      'user_id',
      'disbursement_value',
    ],
    data: {
      value: 500000,
      timelimit: 12,
      disbursement_date: '30 may. 2017',
      payment: 1,
      created_at: '31 dic. 2017',
      fee: 1,
      comments: null,
      state: 3,
      user_full_name: 'N@CHO Montañez Herrera',
      id: 2,
      rate: '0.025',
      is_refinanced: false,
      refinanced_loan: null,
      user_id: 5,
      disbursement_value: null,
    },
    raw: {
      id: 2,
      value: 500000,
      timelimit: 12,
      disbursement_date: '2017-05-30',
      payment: 1,
      created_at: '2018-01-01T00:00:00+00:00',
      fee: 1,
      comments: null,
      state: 3,
      rate: '0.025',
      user_id: 5,
      prev_loan_id: null,
      refinanced_loan: null,
      disbursement_value: null,
      first_name: 'N@CHO',
      last_name: 'Montañez Herrera',
    },
  },
  {
    keys: [
      'value',
      'timelimit',
      'disbursement_date',
      'payment',
      'created_at',
      'fee',
      'comments',
      'state',
      'user_full_name',
      'id',
      'rate',
      'is_refinanced',
      'refinanced_loan',
      'user_id',
      'disbursement_value',
    ],
    data: {
      value: 1372,
      timelimit: 12,
      disbursement_date: '26 mar. 2018',
      payment: 0,
      created_at: '26 mar. 2018',
      fee: 1,
      comments: 'Refinanciar el crédito # 09',
      state: 2,
      user_full_name: 'Hector Ignacio Montañez Daza',
      id: 25,
      rate: '0.025',
      is_refinanced: false,
      refinanced_loan: null,
      user_id: 11,
      disbursement_value: null,
    },
    raw: {
      id: 25,
      value: 1372,
      timelimit: 12,
      disbursement_date: '2018-03-26',
      payment: 0,
      created_at: '2018-03-26T15:34:35.735280+00:00',
      fee: 1,
      comments: 'Refinanciar el crédito # 09',
      state: 2,
      rate: '0.025',
      user_id: 11,
      prev_loan_id: null,
      refinanced_loan: null,
      disbursement_value: null,
      first_name: 'Hector Ignacio',
      last_name: 'Montañez Daza',
    },
  },
  {
    keys: [
      'value',
      'timelimit',
      'disbursement_date',
      'payment',
      'created_at',
      'fee',
      'comments',
      'state',
      'user_full_name',
      'id',
      'rate',
      'is_refinanced',
      'refinanced_loan',
      'user_id',
      'disbursement_value',
    ],
    data: {
      value: 1372000,
      timelimit: 12,
      disbursement_date: '26 mar. 2018',
      payment: 1,
      created_at: '26 mar. 2018',
      fee: 1,
      comments: 'Refinanciar crédito #09',
      state: 3,
      user_full_name: 'Hector Ignacio Montañez Daza',
      id: 26,
      rate: '0.025',
      is_refinanced: false,
      refinanced_loan: 80,
      user_id: 11,
      disbursement_value: null,
    },
    raw: {
      id: 26,
      value: 1372000,
      timelimit: 12,
      disbursement_date: '2018-03-26',
      payment: 1,
      created_at: '2018-03-26T15:37:11.079132+00:00',
      fee: 1,
      comments: 'Refinanciar crédito #09',
      state: 3,
      rate: '0.025',
      user_id: 11,
      prev_loan_id: null,
      refinanced_loan: 80,
      disbursement_value: null,
      first_name: 'Hector Ignacio',
      last_name: 'Montañez Daza',
    },
  },
  {
    keys: [
      'value',
      'timelimit',
      'disbursement_date',
      'payment',
      'created_at',
      'fee',
      'comments',
      'state',
      'user_full_name',
      'id',
      'rate',
      'is_refinanced',
      'refinanced_loan',
      'user_id',
      'disbursement_value',
    ],
    data: {
      value: 2000000,
      timelimit: 6,
      disbursement_date: '6 jun. 2018',
      payment: 0,
      created_at: '6 jun. 2018',
      fee: 1,
      comments: 'Para deuda de juanse y unificar 1 credito por el total de deuda',
      state: 2,
      user_full_name: 'Julio César Montañez Herrera',
      id: 30,
      rate: '0.020',
      is_refinanced: false,
      refinanced_loan: null,
      user_id: 10,
      disbursement_value: null,
    },
    raw: {
      id: 30,
      value: 2000000,
      timelimit: 6,
      disbursement_date: '2018-06-06',
      payment: 0,
      created_at: '2018-06-06T18:15:09.230845+00:00',
      fee: 1,
      comments: 'Para deuda de juanse y unificar 1 credito por el total de deuda',
      state: 2,
      rate: '0.020',
      user_id: 10,
      prev_loan_id: null,
      refinanced_loan: null,
      disbursement_value: null,
      first_name: 'Julio César',
      last_name: 'Montañez Herrera',
    },
  },
  {
    keys: [
      'value',
      'timelimit',
      'disbursement_date',
      'payment',
      'created_at',
      'fee',
      'comments',
      'state',
      'user_full_name',
      'id',
      'rate',
      'is_refinanced',
      'refinanced_loan',
      'user_id',
      'disbursement_value',
    ],
    data: {
      value: 6000000,
      timelimit: 6,
      disbursement_date: '7 jun. 2018',
      payment: 1,
      created_at: '7 jun. 2018',
      fee: 1,
      comments:
        'Por favor los 50.000 abono a cuenta y el reto oara cubrir creditos anteriores. Y saldo de juanse',
      state: 3,
      user_full_name: 'Julio César Montañez Herrera',
      id: 31,
      rate: '0.020',
      is_refinanced: false,
      refinanced_loan: 60,
      user_id: 10,
      disbursement_value: null,
    },
    raw: {
      id: 31,
      value: 6000000,
      timelimit: 6,
      disbursement_date: '2018-06-07',
      payment: 1,
      created_at: '2018-06-07T17:07:53.475264+00:00',
      fee: 1,
      comments:
        'Por favor los 50.000 abono a cuenta y el reto oara cubrir creditos anteriores. Y saldo de juanse',
      state: 3,
      rate: '0.020',
      user_id: 10,
      prev_loan_id: null,
      refinanced_loan: 60,
      disbursement_value: null,
      first_name: 'Julio César',
      last_name: 'Montañez Herrera',
    },
  },
  {
    keys: [
      'value',
      'timelimit',
      'disbursement_date',
      'payment',
      'created_at',
      'fee',
      'comments',
      'state',
      'user_full_name',
      'id',
      'rate',
      'is_refinanced',
      'refinanced_loan',
      'user_id',
      'disbursement_value',
    ],
    data: {
      value: 1736267,
      timelimit: 6,
      disbursement_date: '26 nov. 2018',
      payment: 2,
      created_at: '26 nov. 2018',
      fee: 1,
      comments: 'Refinanciación del crédito #51, cuyo valor incluye intereses. ',
      state: 3,
      user_full_name: 'Cristina Herrera',
      id: 58,
      rate: '0.020',
      is_refinanced: true,
      refinanced_loan: null,
      user_id: 12,
      disbursement_value: null,
    },
    raw: {
      id: 58,
      value: 1736267,
      timelimit: 6,
      disbursement_date: '2018-11-26',
      payment: 2,
      created_at: '2018-11-26T15:02:35.384507+00:00',
      fee: 1,
      comments: 'Refinanciación del crédito #51, cuyo valor incluye intereses. ',
      state: 3,
      rate: '0.020',
      user_id: 12,
      prev_loan_id: 51,
      refinanced_loan: null,
      disbursement_value: null,
      first_name: 'Cristina',
      last_name: 'Herrera',
    },
  },
  {
    keys: [
      'value',
      'timelimit',
      'disbursement_date',
      'payment',
      'created_at',
      'fee',
      'comments',
      'state',
      'user_full_name',
      'id',
      'rate',
      'is_refinanced',
      'refinanced_loan',
      'user_id',
      'disbursement_value',
    ],
    data: {
      value: 6000000,
      timelimit: 6,
      disbursement_date: '7 dic. 2018',
      payment: 2,
      created_at: '4 dic. 2018',
      fee: 1,
      comments: 'Refinanciación del crédito #31, cuyo valor no incluye intereses. Gracias',
      state: 3,
      user_full_name: 'Julio César Montañez Herrera',
      id: 60,
      rate: '0.020',
      is_refinanced: true,
      refinanced_loan: null,
      user_id: 10,
      disbursement_value: null,
    },
    raw: {
      id: 60,
      value: 6000000,
      timelimit: 6,
      disbursement_date: '2018-12-07',
      payment: 2,
      created_at: '2018-12-04T18:26:59.360437+00:00',
      fee: 1,
      comments: 'Refinanciación del crédito #31, cuyo valor no incluye intereses. Gracias',
      state: 3,
      rate: '0.020',
      user_id: 10,
      prev_loan_id: 31,
      refinanced_loan: null,
      disbursement_value: null,
      first_name: 'Julio César',
      last_name: 'Montañez Herrera',
    },
  },
  {
    keys: [
      'value',
      'timelimit',
      'disbursement_date',
      'payment',
      'created_at',
      'fee',
      'comments',
      'state',
      'user_full_name',
      'id',
      'rate',
      'is_refinanced',
      'refinanced_loan',
      'user_id',
      'disbursement_value',
    ],
    data: {
      value: 29907870,
      timelimit: 24,
      disbursement_date: '7 feb. 2024',
      payment: 1,
      created_at: '5 feb. 2024',
      fee: 0,
      comments: 'Abono cuenta nachon 20786036614 bancolombia compra cartera baco occidente...criss',
      state: 1,
      user_full_name: 'Blanca Judith Nuñez',
      id: 279,
      rate: '0.030',
      is_refinanced: false,
      refinanced_loan: null,
      user_id: 6,
      disbursement_value: 29788238,
    },
    raw: {
      id: 279,
      value: 29907870,
      timelimit: 24,
      disbursement_date: '2024-02-07',
      payment: 1,
      created_at: '2024-02-05T16:08:30.121481+00:00',
      fee: 0,
      comments: 'Abono cuenta nachon 20786036614 bancolombia compra cartera baco occidente...criss',
      state: 1,
      rate: '0.030',
      user_id: 6,
      prev_loan_id: null,
      refinanced_loan: null,
      disbursement_value: 29788238,
      first_name: 'Blanca Judith',
      last_name: 'Nuñez',
    },
  },
  {
    keys: [
      'value',
      'timelimit',
      'disbursement_date',
      'payment',
      'created_at',
      'fee',
      'comments',
      'state',
      'user_full_name',
      'id',
      'rate',
      'is_refinanced',
      'refinanced_loan',
      'user_id',
      'disbursement_value',
    ],
    data: {
      value: 7375212,
      timelimit: 24,
      disbursement_date: '28 feb. 2025',
      payment: 1,
      created_at: '24 feb. 2025',
      fee: 0,
      comments: 'Pagar cr compra de cartera fondo unión ',
      state: 1,
      user_full_name: 'Hector Ignacio Montañez Daza',
      id: 336,
      rate: '0.030',
      is_refinanced: false,
      refinanced_loan: null,
      user_id: 11,
      disbursement_value: 7345711,
    },
    raw: {
      id: 336,
      value: 7375212,
      timelimit: 24,
      disbursement_date: '2025-02-28',
      payment: 1,
      created_at: '2025-02-24T18:27:29.343804+00:00',
      fee: 0,
      comments: 'Pagar cr compra de cartera fondo unión ',
      state: 1,
      rate: '0.030',
      user_id: 11,
      prev_loan_id: null,
      refinanced_loan: null,
      disbursement_value: 7345711,
      first_name: 'Hector Ignacio',
      last_name: 'Montañez Daza',
    },
  },
  {
    keys: [
      'value',
      'timelimit',
      'disbursement_date',
      'payment',
      'created_at',
      'fee',
      'comments',
      'state',
      'user_full_name',
      'id',
      'rate',
      'is_refinanced',
      'refinanced_loan',
      'user_id',
      'disbursement_value',
    ],
    data: {
      value: 3627000,
      timelimit: 12,
      disbursement_date: '18 sept. 2026',
      payment: 1,
      created_at: '5 ago. 2026',
      fee: 0,
      comments: 'Abonar cuenta ',
      state: 0,
      user_full_name: 'Hugo Fernando Montañez Herrera',
      id: 456,
      rate: '0.020',
      is_refinanced: false,
      refinanced_loan: null,
      user_id: 2,
      disbursement_value: 3612492,
    },
    raw: {
      id: 456,
      value: 3627000,
      timelimit: 12,
      disbursement_date: '2026-09-18',
      payment: 1,
      created_at: '2026-08-05T15:24:58.726347+00:00',
      fee: 0,
      comments: 'Abonar cuenta ',
      state: 0,
      rate: '0.020',
      user_id: 2,
      prev_loan_id: null,
      refinanced_loan: null,
      disbursement_value: 3612492,
      first_name: 'Hugo Fernando',
      last_name: 'Montañez Herrera',
    },
  },
]);

export const V1_LOAN_DETAIL_SERIALIZER_FIXTURES: readonly LoanDetailSerializerFixture[] =
  Object.freeze([
    {
      keys: [
        'minimum_payment',
        'total_payment',
        'payday_limit',
        'interests',
        'capital_balance',
        'from_date',
      ],
      data: {
        minimum_payment: 2138137,
        total_payment: 2138137,
        payday_limit: '20 feb. 2018',
        interests: 0,
        capital_balance: 0,
        from_date: '4 jun. 2018',
      },
      raw: {
        minimum_payment: 2138137,
        total_payment: 2138137,
        payday_limit: '2018-02-20',
        interests: 0,
        capital_balance: 0,
        from_date: '2018-06-04',
      },
    },
    {
      keys: [
        'minimum_payment',
        'total_payment',
        'payday_limit',
        'interests',
        'capital_balance',
        'from_date',
      ],
      data: {
        minimum_payment: 650000,
        total_payment: 650000,
        payday_limit: '30 may. 2018',
        interests: 0,
        capital_balance: 0,
        from_date: '4 jun. 2018',
      },
      raw: {
        minimum_payment: 650000,
        total_payment: 650000,
        payday_limit: '2018-05-30',
        interests: 0,
        capital_balance: 0,
        from_date: '2018-06-04',
      },
    },
    {
      keys: [
        'minimum_payment',
        'total_payment',
        'payday_limit',
        'interests',
        'capital_balance',
        'from_date',
      ],
      data: {
        minimum_payment: 2587000,
        total_payment: 2587000,
        payday_limit: '13 jun. 2018',
        interests: 0,
        capital_balance: 0,
        from_date: '4 jun. 2018',
      },
      raw: {
        minimum_payment: 2587000,
        total_payment: 2587000,
        payday_limit: '2018-06-13',
        interests: 0,
        capital_balance: 0,
        from_date: '2018-06-04',
      },
    },
    {
      keys: [
        'minimum_payment',
        'total_payment',
        'payday_limit',
        'interests',
        'capital_balance',
        'from_date',
      ],
      data: {
        minimum_payment: 845000,
        total_payment: 845000,
        payday_limit: '4 jul. 2018',
        interests: 195000,
        capital_balance: 650000,
        from_date: '4 jul. 2017',
      },
      raw: {
        minimum_payment: 845000,
        total_payment: 845000,
        payday_limit: '2018-07-04',
        interests: 195000,
        capital_balance: 650000,
        from_date: '2017-07-04',
      },
    },
  ]);
