/**
 * **Ground truth, captured — not written by hand.**
 *
 * Every row below is the observed outcome of an authenticated request against the *real* v1
 * stack: `Django==2.2.27` + `djangorestframework==3.11.2` (the versions pinned in
 * `~/Projects/Fondo-API/requirements.txt`), configured with v1's exact `REST_FRAMEWORK`
 * settings from `api/settings/base.py`, with `fondo_api/permissions.py` imported verbatim
 * and `fondo_api/models.py:UserProfile` reproduced as a real multi-table-inheritance model
 * so `request.user.userprofile.role` resolves the way it does in production.
 *
 * One request was issued per (view class × HTTP method × role) triple — 14 × 5 × 4 = 280 —
 * and the HTTP status recorded. `200` means the permission stack allowed the request through
 * to the handler; `403` means `APIRolePermission` denied it. No other status occurred.
 *
 * The `PUT`/`DELETE`/`POST`/`PATCH` rows with `allowed: false` for **every** role are the
 * important ones: they are methods v1's `list_permissions` never mentions, and they prove
 * the `except: return False` fallthrough denies rather than opens. `LoanView` `DELETE` is
 * 403 even for ADMIN.
 *
 * Regenerate (rather than edit) if v1's `permissions.py` ever changes — but v1 is frozen
 * (`MIGRATION_PLAN.md` §1), so it will not.
 */
export interface V1RoleMatrixRow {
  readonly view: string;
  readonly method: string;
  readonly role: number;
  /** `true` where the captured v1 status was 200, `false` where it was 403. */
  readonly allowed: boolean;
}

export const V1_ROLE_MATRIX: readonly V1RoleMatrixRow[] = [
  { view: 'LoanView', method: 'GET', role: 0, allowed: true },
  { view: 'LoanView', method: 'GET', role: 1, allowed: true },
  { view: 'LoanView', method: 'GET', role: 2, allowed: true },
  { view: 'LoanView', method: 'GET', role: 3, allowed: true },
  { view: 'LoanView', method: 'POST', role: 0, allowed: true },
  { view: 'LoanView', method: 'POST', role: 1, allowed: true },
  { view: 'LoanView', method: 'POST', role: 2, allowed: true },
  { view: 'LoanView', method: 'POST', role: 3, allowed: true },
  { view: 'LoanView', method: 'PATCH', role: 0, allowed: true },
  { view: 'LoanView', method: 'PATCH', role: 1, allowed: false },
  { view: 'LoanView', method: 'PATCH', role: 2, allowed: true },
  { view: 'LoanView', method: 'PATCH', role: 3, allowed: false },
  { view: 'LoanView', method: 'PUT', role: 0, allowed: false },
  { view: 'LoanView', method: 'PUT', role: 1, allowed: false },
  { view: 'LoanView', method: 'PUT', role: 2, allowed: false },
  { view: 'LoanView', method: 'PUT', role: 3, allowed: false },
  { view: 'LoanView', method: 'DELETE', role: 0, allowed: false },
  { view: 'LoanView', method: 'DELETE', role: 1, allowed: false },
  { view: 'LoanView', method: 'DELETE', role: 2, allowed: false },
  { view: 'LoanView', method: 'DELETE', role: 3, allowed: false },
  { view: 'LoanDetailView', method: 'GET', role: 0, allowed: true },
  { view: 'LoanDetailView', method: 'GET', role: 1, allowed: true },
  { view: 'LoanDetailView', method: 'GET', role: 2, allowed: true },
  { view: 'LoanDetailView', method: 'GET', role: 3, allowed: true },
  { view: 'LoanDetailView', method: 'POST', role: 0, allowed: false },
  { view: 'LoanDetailView', method: 'POST', role: 1, allowed: false },
  { view: 'LoanDetailView', method: 'POST', role: 2, allowed: false },
  { view: 'LoanDetailView', method: 'POST', role: 3, allowed: false },
  { view: 'LoanDetailView', method: 'PATCH', role: 0, allowed: true },
  { view: 'LoanDetailView', method: 'PATCH', role: 1, allowed: false },
  { view: 'LoanDetailView', method: 'PATCH', role: 2, allowed: true },
  { view: 'LoanDetailView', method: 'PATCH', role: 3, allowed: false },
  { view: 'LoanDetailView', method: 'PUT', role: 0, allowed: false },
  { view: 'LoanDetailView', method: 'PUT', role: 1, allowed: false },
  { view: 'LoanDetailView', method: 'PUT', role: 2, allowed: false },
  { view: 'LoanDetailView', method: 'PUT', role: 3, allowed: false },
  { view: 'LoanDetailView', method: 'DELETE', role: 0, allowed: false },
  { view: 'LoanDetailView', method: 'DELETE', role: 1, allowed: false },
  { view: 'LoanDetailView', method: 'DELETE', role: 2, allowed: false },
  { view: 'LoanDetailView', method: 'DELETE', role: 3, allowed: false },
  { view: 'UserDetailView', method: 'GET', role: 0, allowed: true },
  { view: 'UserDetailView', method: 'GET', role: 1, allowed: true },
  { view: 'UserDetailView', method: 'GET', role: 2, allowed: true },
  { view: 'UserDetailView', method: 'GET', role: 3, allowed: true },
  { view: 'UserDetailView', method: 'POST', role: 0, allowed: false },
  { view: 'UserDetailView', method: 'POST', role: 1, allowed: false },
  { view: 'UserDetailView', method: 'POST', role: 2, allowed: false },
  { view: 'UserDetailView', method: 'POST', role: 3, allowed: false },
  { view: 'UserDetailView', method: 'PATCH', role: 0, allowed: true },
  { view: 'UserDetailView', method: 'PATCH', role: 1, allowed: true },
  { view: 'UserDetailView', method: 'PATCH', role: 2, allowed: true },
  { view: 'UserDetailView', method: 'PATCH', role: 3, allowed: true },
  { view: 'UserDetailView', method: 'PUT', role: 0, allowed: false },
  { view: 'UserDetailView', method: 'PUT', role: 1, allowed: false },
  { view: 'UserDetailView', method: 'PUT', role: 2, allowed: false },
  { view: 'UserDetailView', method: 'PUT', role: 3, allowed: false },
  { view: 'UserDetailView', method: 'DELETE', role: 0, allowed: true },
  { view: 'UserDetailView', method: 'DELETE', role: 1, allowed: false },
  { view: 'UserDetailView', method: 'DELETE', role: 2, allowed: false },
  { view: 'UserDetailView', method: 'DELETE', role: 3, allowed: false },
  { view: 'UserView', method: 'GET', role: 0, allowed: true },
  { view: 'UserView', method: 'GET', role: 1, allowed: true },
  { view: 'UserView', method: 'GET', role: 2, allowed: true },
  { view: 'UserView', method: 'GET', role: 3, allowed: true },
  { view: 'UserView', method: 'POST', role: 0, allowed: true },
  { view: 'UserView', method: 'POST', role: 1, allowed: false },
  { view: 'UserView', method: 'POST', role: 2, allowed: false },
  { view: 'UserView', method: 'POST', role: 3, allowed: false },
  { view: 'UserView', method: 'PATCH', role: 0, allowed: true },
  { view: 'UserView', method: 'PATCH', role: 1, allowed: false },
  { view: 'UserView', method: 'PATCH', role: 2, allowed: true },
  { view: 'UserView', method: 'PATCH', role: 3, allowed: false },
  { view: 'UserView', method: 'PUT', role: 0, allowed: false },
  { view: 'UserView', method: 'PUT', role: 1, allowed: false },
  { view: 'UserView', method: 'PUT', role: 2, allowed: false },
  { view: 'UserView', method: 'PUT', role: 3, allowed: false },
  { view: 'UserView', method: 'DELETE', role: 0, allowed: false },
  { view: 'UserView', method: 'DELETE', role: 1, allowed: false },
  { view: 'UserView', method: 'DELETE', role: 2, allowed: false },
  { view: 'UserView', method: 'DELETE', role: 3, allowed: false },
  { view: 'ActivityYearView', method: 'GET', role: 0, allowed: true },
  { view: 'ActivityYearView', method: 'GET', role: 1, allowed: true },
  { view: 'ActivityYearView', method: 'GET', role: 2, allowed: true },
  { view: 'ActivityYearView', method: 'GET', role: 3, allowed: true },
  { view: 'ActivityYearView', method: 'POST', role: 0, allowed: true },
  { view: 'ActivityYearView', method: 'POST', role: 1, allowed: true },
  { view: 'ActivityYearView', method: 'POST', role: 2, allowed: false },
  { view: 'ActivityYearView', method: 'POST', role: 3, allowed: false },
  { view: 'ActivityYearView', method: 'PATCH', role: 0, allowed: false },
  { view: 'ActivityYearView', method: 'PATCH', role: 1, allowed: false },
  { view: 'ActivityYearView', method: 'PATCH', role: 2, allowed: false },
  { view: 'ActivityYearView', method: 'PATCH', role: 3, allowed: false },
  { view: 'ActivityYearView', method: 'PUT', role: 0, allowed: false },
  { view: 'ActivityYearView', method: 'PUT', role: 1, allowed: false },
  { view: 'ActivityYearView', method: 'PUT', role: 2, allowed: false },
  { view: 'ActivityYearView', method: 'PUT', role: 3, allowed: false },
  { view: 'ActivityYearView', method: 'DELETE', role: 0, allowed: false },
  { view: 'ActivityYearView', method: 'DELETE', role: 1, allowed: false },
  { view: 'ActivityYearView', method: 'DELETE', role: 2, allowed: false },
  { view: 'ActivityYearView', method: 'DELETE', role: 3, allowed: false },
  { view: 'ActivityYearDetailView', method: 'GET', role: 0, allowed: true },
  { view: 'ActivityYearDetailView', method: 'GET', role: 1, allowed: true },
  { view: 'ActivityYearDetailView', method: 'GET', role: 2, allowed: true },
  { view: 'ActivityYearDetailView', method: 'GET', role: 3, allowed: true },
  { view: 'ActivityYearDetailView', method: 'POST', role: 0, allowed: true },
  { view: 'ActivityYearDetailView', method: 'POST', role: 1, allowed: true },
  { view: 'ActivityYearDetailView', method: 'POST', role: 2, allowed: false },
  { view: 'ActivityYearDetailView', method: 'POST', role: 3, allowed: false },
  { view: 'ActivityYearDetailView', method: 'PATCH', role: 0, allowed: false },
  { view: 'ActivityYearDetailView', method: 'PATCH', role: 1, allowed: false },
  { view: 'ActivityYearDetailView', method: 'PATCH', role: 2, allowed: false },
  { view: 'ActivityYearDetailView', method: 'PATCH', role: 3, allowed: false },
  { view: 'ActivityYearDetailView', method: 'PUT', role: 0, allowed: false },
  { view: 'ActivityYearDetailView', method: 'PUT', role: 1, allowed: false },
  { view: 'ActivityYearDetailView', method: 'PUT', role: 2, allowed: false },
  { view: 'ActivityYearDetailView', method: 'PUT', role: 3, allowed: false },
  { view: 'ActivityYearDetailView', method: 'DELETE', role: 0, allowed: false },
  { view: 'ActivityYearDetailView', method: 'DELETE', role: 1, allowed: false },
  { view: 'ActivityYearDetailView', method: 'DELETE', role: 2, allowed: false },
  { view: 'ActivityYearDetailView', method: 'DELETE', role: 3, allowed: false },
  { view: 'ActivityDetailView', method: 'GET', role: 0, allowed: true },
  { view: 'ActivityDetailView', method: 'GET', role: 1, allowed: true },
  { view: 'ActivityDetailView', method: 'GET', role: 2, allowed: true },
  { view: 'ActivityDetailView', method: 'GET', role: 3, allowed: true },
  { view: 'ActivityDetailView', method: 'POST', role: 0, allowed: false },
  { view: 'ActivityDetailView', method: 'POST', role: 1, allowed: false },
  { view: 'ActivityDetailView', method: 'POST', role: 2, allowed: false },
  { view: 'ActivityDetailView', method: 'POST', role: 3, allowed: false },
  { view: 'ActivityDetailView', method: 'PATCH', role: 0, allowed: true },
  { view: 'ActivityDetailView', method: 'PATCH', role: 1, allowed: true },
  { view: 'ActivityDetailView', method: 'PATCH', role: 2, allowed: false },
  { view: 'ActivityDetailView', method: 'PATCH', role: 3, allowed: false },
  { view: 'ActivityDetailView', method: 'PUT', role: 0, allowed: false },
  { view: 'ActivityDetailView', method: 'PUT', role: 1, allowed: false },
  { view: 'ActivityDetailView', method: 'PUT', role: 2, allowed: false },
  { view: 'ActivityDetailView', method: 'PUT', role: 3, allowed: false },
  { view: 'ActivityDetailView', method: 'DELETE', role: 0, allowed: true },
  { view: 'ActivityDetailView', method: 'DELETE', role: 1, allowed: true },
  { view: 'ActivityDetailView', method: 'DELETE', role: 2, allowed: false },
  { view: 'ActivityDetailView', method: 'DELETE', role: 3, allowed: false },
  { view: 'LoanAppsView', method: 'GET', role: 0, allowed: false },
  { view: 'LoanAppsView', method: 'GET', role: 1, allowed: false },
  { view: 'LoanAppsView', method: 'GET', role: 2, allowed: false },
  { view: 'LoanAppsView', method: 'GET', role: 3, allowed: false },
  { view: 'LoanAppsView', method: 'POST', role: 0, allowed: true },
  { view: 'LoanAppsView', method: 'POST', role: 1, allowed: true },
  { view: 'LoanAppsView', method: 'POST', role: 2, allowed: true },
  { view: 'LoanAppsView', method: 'POST', role: 3, allowed: true },
  { view: 'LoanAppsView', method: 'PATCH', role: 0, allowed: false },
  { view: 'LoanAppsView', method: 'PATCH', role: 1, allowed: false },
  { view: 'LoanAppsView', method: 'PATCH', role: 2, allowed: false },
  { view: 'LoanAppsView', method: 'PATCH', role: 3, allowed: false },
  { view: 'LoanAppsView', method: 'PUT', role: 0, allowed: false },
  { view: 'LoanAppsView', method: 'PUT', role: 1, allowed: false },
  { view: 'LoanAppsView', method: 'PUT', role: 2, allowed: false },
  { view: 'LoanAppsView', method: 'PUT', role: 3, allowed: false },
  { view: 'LoanAppsView', method: 'DELETE', role: 0, allowed: false },
  { view: 'LoanAppsView', method: 'DELETE', role: 1, allowed: false },
  { view: 'LoanAppsView', method: 'DELETE', role: 2, allowed: false },
  { view: 'LoanAppsView', method: 'DELETE', role: 3, allowed: false },
  { view: 'NotificationView', method: 'GET', role: 0, allowed: false },
  { view: 'NotificationView', method: 'GET', role: 1, allowed: false },
  { view: 'NotificationView', method: 'GET', role: 2, allowed: false },
  { view: 'NotificationView', method: 'GET', role: 3, allowed: false },
  { view: 'NotificationView', method: 'POST', role: 0, allowed: true },
  { view: 'NotificationView', method: 'POST', role: 1, allowed: true },
  { view: 'NotificationView', method: 'POST', role: 2, allowed: true },
  { view: 'NotificationView', method: 'POST', role: 3, allowed: true },
  { view: 'NotificationView', method: 'PATCH', role: 0, allowed: false },
  { view: 'NotificationView', method: 'PATCH', role: 1, allowed: false },
  { view: 'NotificationView', method: 'PATCH', role: 2, allowed: false },
  { view: 'NotificationView', method: 'PATCH', role: 3, allowed: false },
  { view: 'NotificationView', method: 'PUT', role: 0, allowed: false },
  { view: 'NotificationView', method: 'PUT', role: 1, allowed: false },
  { view: 'NotificationView', method: 'PUT', role: 2, allowed: false },
  { view: 'NotificationView', method: 'PUT', role: 3, allowed: false },
  { view: 'NotificationView', method: 'DELETE', role: 0, allowed: false },
  { view: 'NotificationView', method: 'DELETE', role: 1, allowed: false },
  { view: 'NotificationView', method: 'DELETE', role: 2, allowed: false },
  { view: 'NotificationView', method: 'DELETE', role: 3, allowed: false },
  { view: 'FileView', method: 'GET', role: 0, allowed: true },
  { view: 'FileView', method: 'GET', role: 1, allowed: true },
  { view: 'FileView', method: 'GET', role: 2, allowed: true },
  { view: 'FileView', method: 'GET', role: 3, allowed: true },
  { view: 'FileView', method: 'POST', role: 0, allowed: true },
  { view: 'FileView', method: 'POST', role: 1, allowed: false },
  { view: 'FileView', method: 'POST', role: 2, allowed: false },
  { view: 'FileView', method: 'POST', role: 3, allowed: false },
  { view: 'FileView', method: 'PATCH', role: 0, allowed: false },
  { view: 'FileView', method: 'PATCH', role: 1, allowed: false },
  { view: 'FileView', method: 'PATCH', role: 2, allowed: false },
  { view: 'FileView', method: 'PATCH', role: 3, allowed: false },
  { view: 'FileView', method: 'PUT', role: 0, allowed: false },
  { view: 'FileView', method: 'PUT', role: 1, allowed: false },
  { view: 'FileView', method: 'PUT', role: 2, allowed: false },
  { view: 'FileView', method: 'PUT', role: 3, allowed: false },
  { view: 'FileView', method: 'DELETE', role: 0, allowed: false },
  { view: 'FileView', method: 'DELETE', role: 1, allowed: false },
  { view: 'FileView', method: 'DELETE', role: 2, allowed: false },
  { view: 'FileView', method: 'DELETE', role: 3, allowed: false },
  { view: 'FileDetailView', method: 'GET', role: 0, allowed: true },
  { view: 'FileDetailView', method: 'GET', role: 1, allowed: true },
  { view: 'FileDetailView', method: 'GET', role: 2, allowed: true },
  { view: 'FileDetailView', method: 'GET', role: 3, allowed: true },
  { view: 'FileDetailView', method: 'POST', role: 0, allowed: false },
  { view: 'FileDetailView', method: 'POST', role: 1, allowed: false },
  { view: 'FileDetailView', method: 'POST', role: 2, allowed: false },
  { view: 'FileDetailView', method: 'POST', role: 3, allowed: false },
  { view: 'FileDetailView', method: 'PATCH', role: 0, allowed: false },
  { view: 'FileDetailView', method: 'PATCH', role: 1, allowed: false },
  { view: 'FileDetailView', method: 'PATCH', role: 2, allowed: false },
  { view: 'FileDetailView', method: 'PATCH', role: 3, allowed: false },
  { view: 'FileDetailView', method: 'PUT', role: 0, allowed: false },
  { view: 'FileDetailView', method: 'PUT', role: 1, allowed: false },
  { view: 'FileDetailView', method: 'PUT', role: 2, allowed: false },
  { view: 'FileDetailView', method: 'PUT', role: 3, allowed: false },
  { view: 'FileDetailView', method: 'DELETE', role: 0, allowed: false },
  { view: 'FileDetailView', method: 'DELETE', role: 1, allowed: false },
  { view: 'FileDetailView', method: 'DELETE', role: 2, allowed: false },
  { view: 'FileDetailView', method: 'DELETE', role: 3, allowed: false },
  { view: 'UserAppsView', method: 'GET', role: 0, allowed: false },
  { view: 'UserAppsView', method: 'GET', role: 1, allowed: false },
  { view: 'UserAppsView', method: 'GET', role: 2, allowed: false },
  { view: 'UserAppsView', method: 'GET', role: 3, allowed: false },
  { view: 'UserAppsView', method: 'POST', role: 0, allowed: true },
  { view: 'UserAppsView', method: 'POST', role: 1, allowed: true },
  { view: 'UserAppsView', method: 'POST', role: 2, allowed: true },
  { view: 'UserAppsView', method: 'POST', role: 3, allowed: true },
  { view: 'UserAppsView', method: 'PATCH', role: 0, allowed: false },
  { view: 'UserAppsView', method: 'PATCH', role: 1, allowed: false },
  { view: 'UserAppsView', method: 'PATCH', role: 2, allowed: false },
  { view: 'UserAppsView', method: 'PATCH', role: 3, allowed: false },
  { view: 'UserAppsView', method: 'PUT', role: 0, allowed: false },
  { view: 'UserAppsView', method: 'PUT', role: 1, allowed: false },
  { view: 'UserAppsView', method: 'PUT', role: 2, allowed: false },
  { view: 'UserAppsView', method: 'PUT', role: 3, allowed: false },
  { view: 'UserAppsView', method: 'DELETE', role: 0, allowed: false },
  { view: 'UserAppsView', method: 'DELETE', role: 1, allowed: false },
  { view: 'UserAppsView', method: 'DELETE', role: 2, allowed: false },
  { view: 'UserAppsView', method: 'DELETE', role: 3, allowed: false },
  { view: 'AdminView', method: 'GET', role: 0, allowed: true },
  { view: 'AdminView', method: 'GET', role: 1, allowed: false },
  { view: 'AdminView', method: 'GET', role: 2, allowed: false },
  { view: 'AdminView', method: 'GET', role: 3, allowed: false },
  { view: 'AdminView', method: 'POST', role: 0, allowed: false },
  { view: 'AdminView', method: 'POST', role: 1, allowed: false },
  { view: 'AdminView', method: 'POST', role: 2, allowed: false },
  { view: 'AdminView', method: 'POST', role: 3, allowed: false },
  { view: 'AdminView', method: 'PATCH', role: 0, allowed: false },
  { view: 'AdminView', method: 'PATCH', role: 1, allowed: false },
  { view: 'AdminView', method: 'PATCH', role: 2, allowed: false },
  { view: 'AdminView', method: 'PATCH', role: 3, allowed: false },
  { view: 'AdminView', method: 'PUT', role: 0, allowed: false },
  { view: 'AdminView', method: 'PUT', role: 1, allowed: false },
  { view: 'AdminView', method: 'PUT', role: 2, allowed: false },
  { view: 'AdminView', method: 'PUT', role: 3, allowed: false },
  { view: 'AdminView', method: 'DELETE', role: 0, allowed: false },
  { view: 'AdminView', method: 'DELETE', role: 1, allowed: false },
  { view: 'AdminView', method: 'DELETE', role: 2, allowed: false },
  { view: 'AdminView', method: 'DELETE', role: 3, allowed: false },
  { view: 'SavingAccountView', method: 'GET', role: 0, allowed: true },
  { view: 'SavingAccountView', method: 'GET', role: 1, allowed: true },
  { view: 'SavingAccountView', method: 'GET', role: 2, allowed: true },
  { view: 'SavingAccountView', method: 'GET', role: 3, allowed: true },
  { view: 'SavingAccountView', method: 'POST', role: 0, allowed: true },
  { view: 'SavingAccountView', method: 'POST', role: 1, allowed: true },
  { view: 'SavingAccountView', method: 'POST', role: 2, allowed: true },
  { view: 'SavingAccountView', method: 'POST', role: 3, allowed: true },
  { view: 'SavingAccountView', method: 'PATCH', role: 0, allowed: false },
  { view: 'SavingAccountView', method: 'PATCH', role: 1, allowed: false },
  { view: 'SavingAccountView', method: 'PATCH', role: 2, allowed: false },
  { view: 'SavingAccountView', method: 'PATCH', role: 3, allowed: false },
  { view: 'SavingAccountView', method: 'PUT', role: 0, allowed: true },
  { view: 'SavingAccountView', method: 'PUT', role: 1, allowed: false },
  { view: 'SavingAccountView', method: 'PUT', role: 2, allowed: true },
  { view: 'SavingAccountView', method: 'PUT', role: 3, allowed: false },
  { view: 'SavingAccountView', method: 'DELETE', role: 0, allowed: false },
  { view: 'SavingAccountView', method: 'DELETE', role: 1, allowed: false },
  { view: 'SavingAccountView', method: 'DELETE', role: 2, allowed: false },
  { view: 'SavingAccountView', method: 'DELETE', role: 3, allowed: false },
];
