import {
  asPythonDict,
  pyGet,
  pyGetDict,
  pyHas,
  pythonInt,
  PythonKeyError,
  PythonTypeError,
  pythonGreaterThan,
  pythonNotEqual,
  toDjangoBool,
  toDjangoDate,
  toDjangoInt,
  toDjangoSmallInt,
  toDjangoText,
} from './python-obj';
import { DJANGO_TEXT_PREP_FIXTURE } from './python-str.fixture';

/**
 * The CPython behaviours v1's services rely on. Each cell states which v1 line depends on it,
 * because none of these is defensive programming — they decide whether a malformed request is
 * a 404, a 409 or a 500.
 *
 * Moved here from `src/users/` by review condition **C36**, together with the `pythonInt`
 * cases below, which were previously untested: Phases 4, 5 and 8 subscript `request.data` and
 * `int()` a query parameter exactly as Phase 3 does.
 */
describe('python-obj', () => {
  describe('asPythonDict', () => {
    it('accepts a mapping', () => {
      expect(asPythonDict({ a: 1 })).toEqual({ a: 1 });
    });

    it.each([[null], [[1, 2]], ['text'], [5], [true]])(
      'raises TypeError for %p, as `obj["type"]` does on a non-mapping',
      (value) => {
        expect(() => asPythonDict(value)).toThrow(PythonTypeError);
      },
    );
  });

  describe('pyGet / pyHas / pyGetDict', () => {
    it('raises KeyError with Python’s message shape', () => {
      expect(() => pyGet({}, 'type')).toThrow(PythonKeyError);
      expect(() => pyGet({}, 'type')).toThrow("KeyError: 'type'");
    });

    it('returns a present key even when its value is null or undefined', () => {
      expect(pyGet({ birthdate: null }, 'birthdate')).toBeNull();
      expect(pyHas({ birthdate: null }, 'birthdate')).toBe(true);
      expect(pyHas({}, 'birthdate')).toBe(false);
    });

    it('does not see inherited properties — `in` on a dict does not either', () => {
      expect(pyHas({}, 'toString')).toBe(false);
      expect(() => pyGet({}, 'toString')).toThrow(PythonKeyError);
    });

    it('pyGetDict raises KeyError for an absent section and TypeError for a scalar one', () => {
      expect(() => pyGetDict({}, 'personal')).toThrow(PythonKeyError);
      expect(() => pyGetDict({ personal: 5 }, 'personal')).toThrow(PythonTypeError);
    });
  });

  describe('toDjangoInt — `BigIntegerField.get_prep_value`', () => {
    it('accepts integers, bigints and decimal strings', () => {
      expect(toDjangoInt(123, 'x')).toBe(123n);
      expect(toDjangoInt(123n, 'x')).toBe(123n);
      expect(toDjangoInt('123', 'x')).toBe(123n);
      expect(toDjangoInt(' -45 ', 'x')).toBe(-45n);
      expect(toDjangoInt(12312451241243, 'x')).toBe(12312451241243n);
    });

    it('truncates a float, as CPython’s int() does', () => {
      expect(toDjangoInt(2.9, 'x')).toBe(2n);
      expect(toDjangoInt(-2.9, 'x')).toBe(-2n);
    });

    it('maps a boolean to 1/0 — `int(True)` is 1', () => {
      expect(toDjangoInt(true, 'x')).toBe(1n);
      expect(toDjangoInt(false, 'x')).toBe(0n);
    });

    it.each([['abc'], [''], [null], [{}], [[1]]])('raises for %p', (value) => {
      expect(() => toDjangoInt(value, 'identification')).toThrow(PythonTypeError);
    });

    it('toDjangoSmallInt narrows to a number for the role column', () => {
      expect(toDjangoSmallInt('2', 'role')).toBe(2);
    });
  });

  describe('toDjangoBool — `BooleanField.to_python`', () => {
    it.each([
      [true, true],
      [false, false],
      [1, true],
      [0, false],
      ['t', true],
      ['True', true],
      ['1', true],
      ['f', false],
      ['False', false],
      ['0', false],
    ])('maps %p to %p', (input, expected) => {
      expect(toDjangoBool(input, 'notifications')).toBe(expected);
    });

    it.each([['true'], ['yes'], [null], [2], [{}]])('raises for %p, as Django does', (value) => {
      expect(() => toDjangoBool(value, 'notifications')).toThrow(PythonTypeError);
    });
  });

  /**
   * **P5-F1 and D35 together.** `get_prep_value` is `to_python`, which is
   * `if isinstance(value, str) or value is None: return value` and otherwise `str(value)`.
   * Two consequences the old implementation got wrong, both measured on the pinned stack:
   *
   *  * `None` reaches the column as SQL **NULL** — it is never the four characters `'None'`
   *    (**D35**);
   *  * a `list`/`dict` reaches the column as CPython's **repr** — `['a']`, `{'a': 1}` — not
   *    as a type name (**P5-F1**).
   *
   * The table is not transcribed: it is the differential capture in
   * `python-str.fixture.ts`, generated by `scripts/gen-python-str-fixture.py` inside the v1
   * container, so a cell here cannot agree with a wrong belief about CPython.
   */
  describe('toDjangoText — `CharField`/`TextField.get_prep_value`', () => {
    it.each(DJANGO_TEXT_PREP_FIXTURE)('stores %s as the value Django stores', (body, expected) => {
      expect(toDjangoText(JSON.parse(body))).toBe(expected);
    });

    it('returns SQL NULL for None, not the string None (D35)', () => {
      expect(toDjangoText(null)).toBeNull();
      expect(toDjangoText(undefined)).toBeNull();
    });

    it('renders a container as CPython’s repr, not as a type name (P5-F1)', () => {
      expect(toDjangoText(['a'])).toBe("['a']");
      expect(toDjangoText({ a: 1 })).toBe("{'a': 1}");
      expect(toDjangoText([])).toBe('[]');
      expect(toDjangoText({})).toBe('{}');
      expect(toDjangoText({ a: [1, { b: 2 }] })).toBe("{'a': [1, {'b': 2}]}");
    });

    it('leaves the scalars alone — the positive control for the two cells above', () => {
      expect(toDjangoText(true)).toBe('True');
      expect(toDjangoText(false)).toBe('False');
      expect(toDjangoText(5)).toBe('5');
      expect(toDjangoText(5.5)).toBe('5.5');
      expect(toDjangoText('x')).toBe('x');
      expect(toDjangoText('')).toBe('');
    });
  });

  describe('pythonNotEqual — `__update_user_finance`’s change check', () => {
    it('is False for an equal integer, whatever its JavaScript type', () => {
      expect(pythonNotEqual(2000n, 2000)).toBe(false);
      expect(pythonNotEqual(2000n, 2000n)).toBe(false);
    });

    it('is True for a stringified number — Python’s `2000 != "2000"` is True', () => {
      // ⚠️ Deliberately different from `changedFields`, which normalises. This one decides
      // whether v1 would have written the row and bumped `last_modified`.
      expect(pythonNotEqual(2000n, '2000')).toBe(true);
    });

    it('is True for a float that is not the same integer', () => {
      expect(pythonNotEqual(2000n, 2000.5)).toBe(true);
    });

    it('compares booleans by identity, so a stored False differs from "false"', () => {
      expect(pythonNotEqual(false, false)).toBe(false);
      expect(pythonNotEqual(false, 'false')).toBe(true);
      expect(pythonNotEqual(true, false)).toBe(true);
    });

    it('is True for null and for objects', () => {
      expect(pythonNotEqual(1n, null)).toBe(true);
      expect(pythonNotEqual(1n, {})).toBe(true);
    });
  });

  describe('pythonGreaterThan — `create_loan`’s quota gate (`services/loan.py:27`)', () => {
    /**
     * Every expectation in this block was run through CPython before it was written here:
     *
     * ```
     * >>> 1000.5 > 1000, 999.5 > 1000, 1000.0 > 1000
     * (True, False, False)
     * >>> True > 0, True > 1, False > 0, False > -1
     * (True, False, False, True)
     * >>> 9007199254740992.0 > 9007199254740993
     * False
     * ```
     */
    it('is False at the boundary — the check is `>`, not `>=`', () => {
      expect(pythonGreaterThan(500, 500n)).toBe(false);
      expect(pythonGreaterThan(500n, 500n)).toBe(false);
      expect(pythonGreaterThan(501, 500n)).toBe(true);
      expect(pythonGreaterThan(499, 500n)).toBe(false);
    });

    /**
     * ⚠️ **D29's divergent window, and the whole reason this helper exists.** A fractional
     * value strictly between the quota and the quota + 1 is *greater* raw — v1's 406 — and
     * *equal* once `toDjangoInt` has truncated it, which is the 201 v2 used to answer while
     * storing a number the member never submitted.
     */
    it('is True for a fraction inside `(quota, quota + 1)`, where truncation says equal', () => {
      expect(pythonGreaterThan(500.5, 500n)).toBe(true);
      expect(toDjangoInt(500.5, 'value')).toBe(500n); // …and this is why ordering matters
      expect(pythonGreaterThan(500.000001, 500n)).toBe(true);
    });

    it('is False for a fraction below the quota — both stacks accept and both store the floor', () => {
      expect(pythonGreaterThan(499.5, 500n)).toBe(false);
      expect(pythonGreaterThan(-0.5, -1n)).toBe(true);
    });

    it('treats a bool as an int, as Python’s subclassing does', () => {
      expect(pythonGreaterThan(true, 0n)).toBe(true);
      expect(pythonGreaterThan(true, 1n)).toBe(false);
      expect(pythonGreaterThan(false, 0n)).toBe(false);
      expect(pythonGreaterThan(false, -1n)).toBe(true);
    });

    /** CPython compares an `int` and a `float` **exactly**; it never rounds the int. */
    it('compares exactly beyond 2^53, where a double round-trip would lie', () => {
      expect(pythonGreaterThan(9_007_199_254_740_992, 9_007_199_254_740_993n)).toBe(false);
      expect(pythonGreaterThan(9_007_199_254_740_994, 9_007_199_254_740_993n)).toBe(true);
    });

    it('is False for NaN — every comparison with nan is False in Python', () => {
      expect(pythonGreaterThan(Number.NaN, 0n)).toBe(false);
      expect(pythonGreaterThan(Number.POSITIVE_INFINITY, 0n)).toBe(true);
      expect(pythonGreaterThan(Number.NEGATIVE_INFINITY, 0n)).toBe(false);
    });

    /**
     * ⚠️ The helper stays faithful to CPython here. **D29's leniency for a string lives at
     * `createLoan`'s call site**, which coerces before comparing — deliberately, so the
     * deviation is visible where it is taken rather than hidden in a shared helper Phases 5–8
     * will reuse.
     */
    it.each([
      ['1000', "'>' not supported between instances of 'str' and 'int'"],
      [null, "'>' not supported between instances of 'NoneType' and 'int'"],
      [{}, "'>' not supported between instances of 'dict' and 'int'"],
      [[], "'>' not supported between instances of 'list' and 'int'"],
    ])('raises CPython’s TypeError for %p, which v1 never catches', (value, message) => {
      expect(() => pythonGreaterThan(value, 1n)).toThrow(PythonTypeError);
      expect(() => pythonGreaterThan(value, 1n)).toThrow(message);
    });
  });

  describe('toDjangoDate — `DateField.to_python` / `dateparse.parse_date`', () => {
    it('accepts a zero-padded date', () => {
      expect(toDjangoDate('2018-01-01', 'd')).toEqual({ year: 2018, month: 1, day: 1 });
    });

    /**
     * ⚠️ The regex is `\d{1,2}` for month and day, and v1's own loan fixtures rely on it:
     * `test_loan_views.py:64` posts `'2017-12-9'` and `:110` posts `'2018-1-1'`. A
     * `YYYY-MM-DD`-only implementation refuses bodies v1 accepts and writes.
     */
    it('accepts an UNPADDED month and day, as Django’s date_re does', () => {
      expect(toDjangoDate('2017-12-9', 'd')).toEqual({ year: 2017, month: 12, day: 9 });
      expect(toDjangoDate('2018-1-1', 'd')).toEqual({ year: 2018, month: 1, day: 1 });
      expect(toDjangoDate('2018-1-15', 'd')).toEqual({ year: 2018, month: 1, day: 15 });
    });

    it('accepts one trailing newline, because Python’s `$` matches before it', () => {
      expect(toDjangoDate('2018-01-01\n', 'd')).toEqual({ year: 2018, month: 1, day: 1 });
    });

    it('rejects two trailing newlines — `$` allows exactly one', () => {
      expect(() => toDjangoDate('2018-01-01\n\n', 'd')).toThrow(/invalid date format/);
    });

    it.each([
      '',
      '18-01-01',
      '2018/01/01',
      '01-01-2018',
      '2018-01-01T00:00:00',
      ' 2018-01-01',
      'abc',
    ])('rejects %p with a ValidationError', (value) => {
      expect(() => toDjangoDate(value, 'd')).toThrow(/invalid date format/);
    });

    it('rejects an out-of-range date after the regex matches — Django’s invalid_date branch', () => {
      expect(() => toDjangoDate('2018-13-01', 'd')).toThrow(/invalid date/);
      expect(() => toDjangoDate('2018-02-30', 'd')).toThrow(/invalid date/);
      expect(() => toDjangoDate('2019-02-29', 'd')).toThrow(/invalid date/);
      expect(() => toDjangoDate('2018-00-01', 'd')).toThrow(/invalid date/);
      expect(() => toDjangoDate('2018-01-00', 'd')).toThrow(/invalid date/);
    });

    it('accepts 29 February in a leap year, including the century rule', () => {
      expect(toDjangoDate('2020-02-29', 'd')).toEqual({ year: 2020, month: 2, day: 29 });
      expect(toDjangoDate('2000-02-29', 'd')).toEqual({ year: 2000, month: 2, day: 29 });
      expect(() => toDjangoDate('2100-02-29', 'd')).toThrow(/invalid date/);
    });

    it('a non-string is a TypeError from `re.match`, which to_python does NOT catch', () => {
      expect(() => toDjangoDate(20180101, 'd')).toThrow(/TypeError/);
      expect(() => toDjangoDate(null, 'd')).toThrow(/TypeError/);
      expect(() => toDjangoDate({ year: 2018 }, 'd')).toThrow(/TypeError/);
    });

    it('names the field in the message, so a 500 log says which column failed', () => {
      expect(() => toDjangoDate('nope', 'disbursement_date')).toThrow(/disbursement_date/);
    });
  });

  describe('pythonInt — CPython `int(str)`', () => {
    it('parses a plain decimal', () => {
      expect(pythonInt('12')).toBe(12);
    });

    it('allows surrounding whitespace and a sign, as int() does', () => {
      expect(pythonInt('  7  ')).toBe(7);
      expect(pythonInt('+7')).toBe(7);
      expect(pythonInt('-7')).toBe(-7);
    });

    it('raises ValueError for an empty string — `?page=` is a 500, not a 400', () => {
      expect(() => pythonInt('')).toThrow("ValueError: invalid literal for int() with base 10: ''");
    });

    it('raises ValueError for a non-integer, quoting the RAW value in the message', () => {
      expect(() => pythonInt('abc')).toThrow(
        "ValueError: invalid literal for int() with base 10: 'abc'",
      );
      // Not the trimmed one: CPython echoes what it was given.
      expect(() => pythonInt(' 1.5 ')).toThrow(
        "ValueError: invalid literal for int() with base 10: ' 1.5 '",
      );
    });

    it('refuses a float, a hex literal and an underscored literal', () => {
      for (const raw of ['1.0', '0x10', '1e3']) {
        expect(() => pythonInt(raw)).toThrow('ValueError');
      }
    });
  });
});
