/**
 * CPython's `str()` and `repr()` for the shapes a parsed JSON body can carry.
 *
 * ## Why this module exists at all
 *
 * Django coerces on the way to the column: `CharField`/`TextField.get_prep_value` is
 * `to_python`, which is `str(value)` for anything that is not already a `str` or `None`.
 * Nothing in v1 validates a request body, so **whatever the client sent is what `str()` gets**
 * — including a list or a dict. Parity finding **P5-F1** was a v2 that stored the *type name*
 * (`'list'`, `'object'`) there, because {@link toDjangoText} reached for a helper whose own
 * docblock said it was "for an error message".
 *
 * The split this module enforces:
 *
 * | concern | function | may reach a column? |
 * |---|---|---|
 * | what CPython's `str()` renders | {@link pythonStr} | yes — used by `toDjangoText` |
 * | what CPython's `repr()` renders | {@link pythonRepr} | yes — `str()` of a container *is* its repr |
 * | naming a type inside a 500's message | `describeTypeForErrorMessage` (private to `python-obj.ts`) | **no** |
 *
 * ## Where the expected values come from
 *
 * `python-str.fixture.ts` is a **differential capture**, generated by
 * `scripts/gen-python-str-fixture.py` run inside the pinned v1 container
 * (CPython 3.9.25 / Django 2.2.27) against `TextField().get_prep_value(json.loads(body))`.
 * It is not a transcription of what anyone believes CPython does.
 *
 * ## Known limits, stated rather than hidden
 *
 * **Two** of them, both rooted in what `JSON.parse` throws away before this module is reached,
 * and each would need a bespoke JSON scanner to close (v2 already has one for error messages,
 * `common/http/python-json.ts`, but it does not build values). Neither is reachable from the
 * fund's clients, which send strings and numbers, not containers, to the text columns.
 *
 *  1. **`int` vs `float` — JSON does not record which one the author wrote.** `json.loads`
 *     keeps the distinction (`'5'` is an `int`, `'5.0'` a `float`); `JSON.parse` collapses
 *     both onto a double. This module therefore renders every number the way CPython renders a
 *     **`float`** when the value has a fractional part — exactly, since {@link reprNumber}
 *     now carries CPython's exponential threshold — and the way CPython renders an **`int`**
 *     when the value is integral. Three shapes diverge, all of them integral-valued:
 *
 *     | body | v1 stores | v2 stores | why |
 *     |---|---|---|---|
 *     | `5.0` | `5.0` | `5` | CPython's `ADD_DOT_0`; the `.0` cannot be recovered |
 *     | `-0.0` | `-0.0` | `0` | `String(-0)` is `'0'`; `json.loads('-0')` is the `int` `0` |
 *     | `10000000000000000` | `10000000000000000` | `1e+16` | an `int` at or beyond `decpt > 16` is indistinguishable from the `float` `1e16`, which v1 *also* renders `1e+16` |
 *
 *     The third row is where the old limit 2 ("very large integers", stated at `10**21`) has
 *     gone: it was the same rule with the JS threshold rather than CPython's, so it named the
 *     wrong boundary. Below `1e16` every `int` agrees byte for byte.
 *  2. **`dict` key order.** CPython preserves document order; a JS object reorders
 *     integer-like keys ahead of the rest, so `{"b":1,"1":2}` renders `{'1': 2, 'b': 1}` here
 *     and `{'b': 1, '1': 2}` in v1.
 *
 * Each row above is a **cell**, not a claim: `DJANGO_TEXT_PREP_DIVERGENCES` carries v1's value
 * captured from the container and `python-obj.spec.ts` carries v2's beside it, so a limit that
 * is silently closed, silently widened, or quietly stops being true fails a test.
 *
 * ### How this list was established as complete, rather than merely shorter
 *
 * By differential sweep against the pinned container, not by reading the code. Two runs, the
 * same body list fed to `TextField().get_prep_value(json.loads(b))` in the container and to
 * `toDjangoText(JSON.parse(b))` under `ts-node`:
 *
 * * **8 967 numeric bodies** — every `decpt` from -330 to +24 with four mantissa shapes, the
 *   fixed-notation neighbourhood of both thresholds, the integral values around `1e16`…`1e23`,
 *   and 6 000 seeded randoms including 3 000 drawn from raw 64-bit patterns. **117 divergences,
 *   all three of them classes of limit 1** (92 `ADD_DOT_0`, 17 large-`int` literals, 8 negative
 *   zero) and **zero unclassified**.
 * * **5 951 string and container bodies** — every code point below U+0120 plus the boundary
 *   ones, the quote-selection matrix, integer-like key orders, 2 000 random nested containers
 *   and 3 000 random astral strings. Against the **pre-fix** build: 76 divergences, 9 dict key
 *   order and **67 Unicode-database skew**, zero unclassified. The skew was a real finding and
 *   is **closed**, not declared — see {@link isPythonNonPrintable} — so the same sweep against
 *   the build you are reading reports **9 divergences, all of them limit 2, zero
 *   unclassified.**
 *
 * The sweep is a discriminator, not an agreement check, and it was run in the failing
 * direction first: against the pre-fix build it reports the two exponential bands and the
 * 67 skew rows as well, which is how both were found. "Complete" here means *every* divergence
 * the two sweeps produce is classified into one of the two limits above and none is left over
 * — not "I looked and saw nothing".
 */

import { PYTHON_DECIMAL_DIGIT_RANGES, PYTHON_NONPRINTABLE_RANGES } from './python-str.fixture';

/**
 * CPython's `str.isprintable()`, negated:
 *
 * > Nonprintable characters are those characters defined in the Unicode character database as
 * > "Other" or "Separator", excepting the ASCII space.
 *
 * i.e. general categories `Cc Cf Cs Co Cn Zl Zp Zs`, minus U+0020.
 *
 * ## Why this is a table and not `/\p{Cc}\p{Cf}…/u`
 *
 * It **was** that regex, and the regex is wrong — not in its category list, which is right, but
 * in *whose* Unicode database answers it. `Cn` means "unassigned", so the predicate moves every
 * time either runtime's UCD moves, and the two are eleven years apart: the pinned v1 is CPython
 * 3.9.25 on **UCD 13.0.0**, Node 24 is on **UCD 17.0**. Every code point assigned between them
 * is `Cn` (escaped) in v1 and a printable letter (stored literally) in v2.
 *
 * Measured by enumerating all 1 114 112 code points in both runtimes and diffing the predicate:
 * **15 933 code points disagreed, all in the same direction** — v1 escapes, v2 stored the
 * character. 161 ranges, including U+0870–U+088F (Arabic Extended-B), U+11FB0, U+1E7E0 and the
 * CJK Ext-G/H additions. It is the largest divergence this module ever had and no cell could
 * have seen it, because the 41-row fixture samples code points that were assigned in 2020.
 *
 * So the answer is captured from the pinned interpreter rather than asked of the local one:
 * `PYTHON_NONPRINTABLE_RANGES` is `str.isprintable()` for every code point, generated by
 * `scripts/gen-python-str-fixture.py` in the container. That also makes the module immune to a
 * Node upgrade, which the regex was not — a UCD 18 would have silently re-opened the same gap.
 *
 * The ranges are ascending, non-overlapping and flat (`[start, end, start, end, …]`), so the
 * lookup is a binary search on even indices.
 */
export function isPythonNonPrintable(codePoint: number): boolean {
  let lo = 0;
  let hi = PYTHON_NONPRINTABLE_RANGES.length / 2 - 1;
  while (lo <= hi) {
    const mid = (lo + hi) >> 1;
    if (codePoint < PYTHON_NONPRINTABLE_RANGES[mid * 2]) {
      hi = mid - 1;
    } else if (codePoint > PYTHON_NONPRINTABLE_RANGES[mid * 2 + 1]) {
      lo = mid + 1;
    } else {
      return true;
    }
  }
  return false;
}

/**
 * CPython's `unicode_escape`-style widths inside a `repr`:
 * `\xNN` below U+0100, `\uNNNN` below U+10000, `\UNNNNNNNN` above. Lowercase hex, as CPython
 * emits (`repr(U+200B ZERO WIDTH SPACE)` -> `"'\\u200b'"`, `repr('\U000e0001')` -> `"'\\U000e0001'"`).
 */
function escapeCodePoint(codePoint: number): string {
  if (codePoint < 0x100) {
    return `\\x${codePoint.toString(16).padStart(2, '0')}`;
  }
  if (codePoint < 0x10000) {
    return `\\u${codePoint.toString(16).padStart(4, '0')}`;
  }
  return `\\U${codePoint.toString(16).padStart(8, '0')}`;
}

/**
 * CPython's `unicode_repr` (`Objects/unicodeobject.c`).
 *
 * The quote rule is the one people get wrong: the default is `'`, and it switches to `"`
 * **only** when the string contains a `'` and no `"`. Measured:
 * `str(["a'b"])` -> `["a'b"]`, `str(['a"b'])` -> `['a"b']`, `str(["a'b\"c"])` -> `['a\'b"c']`.
 */
function reprString(value: string): string {
  const quote = value.includes("'") && !value.includes('"') ? '"' : "'";
  let out = quote;
  for (const character of value) {
    if (character === quote || character === '\\') {
      out += `\\${character}`;
    } else if (character === '\t') {
      out += '\\t';
    } else if (character === '\n') {
      out += '\\n';
    } else if (character === '\r') {
      out += '\\r';
    } else if (isPythonNonPrintable(character.codePointAt(0) as number)) {
      out += escapeCodePoint(character.codePointAt(0) as number);
    } else {
      out += character;
    }
  }
  return out + quote;
}

/**
 * `repr(float)` / `str(float)` — identical in Python 3.
 *
 * JavaScript and CPython agree on the shortest round-tripping *digits*. They disagree on two
 * things, and both are ported here:
 *
 *  1. **When to switch to exponential notation.** CPython's `format_float_short`
 *     (`Python/pystrtod.c`, repr mode `'r'`) uses exponential iff `decpt <= -4 || decpt > 16`,
 *     where `decpt` is the position of the decimal point relative to the first significant
 *     digit. ECMA-262's `Number::toString` uses fixed notation for `-6 < n <= 21` — i.e.
 *     exponential iff `decpt <= -6 || decpt > 21`. Two bands therefore diverge, one at each end:
 *
 *     | `decpt` | value example | CPython | JS `String()` |
 *     |---|---|---|---|
 *     | `-5`, `-4` | `1e-5` (`decpt = -4`) | `1e-05` | `0.00001` |
 *     | `17`–`21` | `1e16` (`decpt = 17`) | `1e+16` | `10000000000000000` |
 *
 *     Measured in the pinned container, not derived: `0.00001 -> '1e-05'`,
 *     `1.5e-5 -> '1.5e-05'`, `1e16 -> '1e+16'`, `1e17 -> '1e+17'`. Review finding **C60**;
 *     before the fix v2 stored the JS column of that table.
 *  2. **The exponent's minimum width**, which CPython pads to two digits (`str(1e-7)` is
 *     `'1e-07'`, JS gives `'1e-7'`). Three-digit exponents are not padded further
 *     (`1e-323 -> '1e-323'` on both).
 *
 * `inf`/`-inf`/`nan` are CPython's spellings; `JSON.parse` cannot produce them, but
 * `json.loads` can, so they are covered.
 *
 * Note what is deliberately *not* reproduced: CPython's `Py_DTSF_ADD_DOT_0`, which makes an
 * integral float render as `5.0`. That is unreachable from here — `JSON.parse` has already
 * thrown away the distinction between `5` and `5.0` — and it is limit 1 in the block above.
 */
function reprNumber(value: number): string {
  if (Number.isNaN(value)) {
    return 'nan';
  }
  if (value === Infinity) {
    return 'inf';
  }
  if (value === -Infinity) {
    return '-inf';
  }
  // `toExponential()` with no argument is specified to emit the shortest digit string that
  // round-trips — the same digits CPython gets from `_Py_dg_dtoa` mode 0 — so `decpt` can be
  // read off it without re-deriving the shortest form.
  const [mantissa, exponent] = value.toExponential().split('e');
  const decpt = Number(exponent) + 1;
  if (decpt > -4 && decpt <= 16) {
    // CPython uses fixed notation here, and so does JS (this band is inside `-6 < n <= 21`),
    // with the same digits — so `String()` is already the answer.
    return String(value);
  }
  const sign = decpt <= 0 ? '-' : '+';
  return `${mantissa}e${sign}${String(Math.abs(decpt - 1)).padStart(2, '0')}`;
}

/**
 * CPython's `repr()`.
 *
 * `str()` and `repr()` differ for exactly one of the JSON shapes — a `str`, where `str()` is
 * the identity and `repr()` quotes — so {@link pythonStr} is this function with that one case
 * short-circuited. A container's `str()` *is* its `repr()`, and it reprs its elements, which
 * is why `str({'a': 'b'})` is `{'a': 'b'}` and not `{a: b}`.
 */
export function pythonRepr(value: unknown): string {
  if (value === null || value === undefined) {
    return 'None';
  }
  if (typeof value === 'boolean') {
    return value ? 'True' : 'False';
  }
  if (typeof value === 'string') {
    return reprString(value);
  }
  if (typeof value === 'bigint') {
    return value.toString();
  }
  if (typeof value === 'number') {
    return reprNumber(value);
  }
  if (Array.isArray(value)) {
    return `[${value.map(pythonRepr).join(', ')}]`;
  }
  // `', '` between items and `': '` after a key — the spaces are part of the stored string.
  return `{${Object.entries(value as Record<string, unknown>)
    .map(([key, item]) => `${reprString(key)}: ${pythonRepr(item)}`)
    .join(', ')}}`;
}

/**
 * CPython's `str()`.
 *
 * This is what `'{}'.format(x)`, `'%s' % x` and `force_bytes(x)` produce, and therefore what
 * `refinance_loan`'s comment concatenation (`services/loan.py:141`) and
 * `set_password`'s hasher (`django.contrib.auth.hashers`) see. It is **not** the same
 * question as "what does Django store": a `None` is the four characters `None` here and SQL
 * `NULL` there. `toDjangoText` is the storage answer.
 */
/**
 * CPython's `str.strip()` with no argument - the character set is **not** JS `trim()`'s.
 *
 * `str.strip()` removes characters for which `str.isspace()` is true: Unicode category `Zs`
 * plus bidirectional class `WS`/`B`/`S`, which pulls in the C0 separators U+001C-U+001F and
 * U+0085 (NEL). `String.prototype.trim()` removes Unicode `White_Space` **plus U+FEFF**.
 *
 * Measured against the pinned container, they disagree in both directions:
 *
 * | codepoint | CPython `strip()` | JS `trim()` |
 * |---|---|---|
 * | U+001C-U+001F, U+0085 | strips | keeps |
 * | U+FEFF (BOM / ZWNBSP) | keeps | strips |
 *
 * So `trim()` is not a faithful port - it would trade one divergence for two smaller ones.
 * U+200B (ZERO WIDTH SPACE) is whitespace to neither and is stripped by neither.
 */
const PYTHON_SPACE =
  '\\t\\n\\v\\f\\r\\u001c-\\u001f \\u0085\\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000';
const PYTHON_STRIP_RE = new RegExp(`^[${PYTHON_SPACE}]+|[${PYTHON_SPACE}]+$`, 'gu');

export function pythonStrip(value: string): string {
  return value.replace(PYTHON_STRIP_RE, '');
}

/**
 * The whitespace CPython's **`int(str)`** skips — which is neither `trim()`'s set **nor
 * {@link pythonStrip}'s**, and that third answer is the whole point of this constant.
 *
 * `int()` does not call `strip()`. It scans with `Py_UNICODE_ISSPACE`, and that macro's ASCII
 * table covers `\t\n\v\f\r` and space but **not** the C0 separators U+001C-U+001F, which
 * `str.isspace()` (and therefore `strip()`) does accept. Measured in the pinned container over
 * 25 code points, `int(ch + '5' + ch)` against `(ch + '5' + ch).strip()`:
 *
 * | code point | `int()` | `strip()` | JS `trim()` |
 * |---|---|---|---|
 * | U+0009-U+000D, U+0020 | skips | strips | strips |
 * | U+00A0, U+1680, U+2000-U+200A, U+2028, U+2029, U+202F, U+205F, U+3000 | skips | strips | strips |
 * | **U+0085** (NEL) | **skips** | strips | **keeps** — v1 answers, v2 used to 500 |
 * | **U+001C-U+001F** | **ValueError** | **strips** | keeps |
 * | **U+FEFF** (BOM) | **ValueError** | keeps | **strips** — v1 500s, v2 used to answer |
 * | U+200B, U+180E | ValueError | keeps | keeps |
 *
 * So routing `int()` through `pythonStrip` would fix U+0085 and U+FEFF and **break**
 * U+001C-U+001F, which currently agree by accident. Review condition **C63**; the divergence
 * is reachable from `?page=` on `GET /api/user` and `GET /api/loan`, where v1's `int()` is
 * unguarded (P4-D4), and from `value` / `identification` / `state` in a body.
 */
const PYTHON_INT_SPACE =
  '\\t\\n\\v\\f\\r \\u0085\\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000';
const PYTHON_INT_STRIP_RE = new RegExp(`^[${PYTHON_INT_SPACE}]+|[${PYTHON_INT_SPACE}]+$`, 'gu');

/**
 * `str.strip()` restricted to the set CPython's `int()` skips. See {@link PYTHON_INT_SPACE}
 * for why this is not {@link pythonStrip}.
 */
export function pythonIntStrip(value: string): string {
  return value.replace(PYTHON_INT_STRIP_RE, '');
}

/**
 * The digit value CPython's `int()` assigns a code point, or `-1` for a code point it does not
 * read as a digit at all.
 *
 * ## Why this is a table and not `/\p{Nd}/u`
 *
 * Same reason as {@link isPythonNonPrintable}, and it was found the same way. `int()` does not
 * test a *category*: `PyLong_FromUnicodeObject` first runs
 * `_PyUnicode_TransformDecimalAndSpaceToASCII`, which folds every code point whose
 * `Py_UNICODE_TODECIMAL` is non-negative onto the matching ASCII digit. On the pinned
 * interpreter that set is **exactly** category `Nd` and the value is always
 * `(cp - run_start) % 10` — both asserted by the generator over all 1 114 112 code points, not
 * assumed.
 *
 * But `Nd` moves, and the two runtimes are eleven years apart: CPython 3.9.25 is on **UCD
 * 13.0.0** with **650** such code points, Node 24 is on **UCD 17.0** with **770**. Writing
 * `\p{Nd}` would accept **120 code points v1 refuses** — Tangsa, Kawi, Nag Mundari, Gurung
 * Khema, Kirat Rai, Ol Onal, Sunuwar, Garay and the rest of the digit sets assigned since 2020
 * — turning a v1 `ValueError` (a 500) into a v2 success. So the answer is captured from the
 * pinned interpreter: `PYTHON_DECIMAL_DIGIT_RANGES`, generated by
 * `scripts/gen-python-str-fixture.py`, ascending, non-overlapping, flat `[start, end, …]`
 * pairs, searched on even indices.
 *
 * The one run that is not ten code points wide is U+1D7CE–U+1D7FF (the five mathematical digit
 * alphabets, 50 code points), which is why the value is `% 10` rather than a plain subtraction.
 */
function pythonDecimalDigitValue(codePoint: number): number {
  let lo = 0;
  let hi = PYTHON_DECIMAL_DIGIT_RANGES.length / 2 - 1;
  while (lo <= hi) {
    const mid = (lo + hi) >> 1;
    const start = PYTHON_DECIMAL_DIGIT_RANGES[mid * 2];
    if (codePoint < start) {
      hi = mid - 1;
    } else if (codePoint > PYTHON_DECIMAL_DIGIT_RANGES[mid * 2 + 1]) {
      lo = mid + 1;
    } else {
      return (codePoint - start) % 10;
    }
  }
  return -1;
}

/**
 * CPython's `_PyUnicode_TransformDecimalAndSpaceToASCII` (`Objects/unicodeobject.c`), the pass
 * `int(str)` runs **before** it parses anything:
 *
 * ```c
 * for (i = 0; i < len; ++i) {
 *     Py_UCS4 ch = PyUnicode_READ(kind, data, i);
 *     if (ch < 127)                       continue;              // ASCII: untouched
 *     if (Py_UNICODE_ISSPACE(ch))         { out = ' '; continue; }
 *     decimal = Py_UNICODE_TODECIMAL(ch);
 *     if (decimal < 0)                    { out = ch; ... }       // left alone, parse fails
 *     out = '0' + decimal;
 * }
 * ```
 *
 * ⚠️ **Only digits and spaces are folded — nothing else.** That asymmetry is the whole
 * behaviour and getting it wrong in either direction is observable:
 *
 * | input | CPython | why |
 * |---|---|---|
 * | `'１'` U+FF11 FULLWIDTH ONE | `1` | `Nd`, folded |
 * | `'١'` U+0661 ARABIC-INDIC ONE | `1` | `Nd`, folded |
 * | `'۱'` U+06F1 EXTENDED ARABIC-INDIC ONE | `1` | `Nd`, folded |
 * | `'１２３'` | `123` | folded digit by digit |
 * | `'1１'` mixed scripts | `11` | no "same script" rule exists |
 * | **`'＋1'`** U+FF0B FULLWIDTH PLUS | **`ValueError`** | `Pf`/`Sm`, **not** folded — the sign must be ASCII |
 * | **`'－1'`** U+FF0D FULLWIDTH HYPHEN-MINUS | **`ValueError`** | same |
 *
 * All seven measured in the pinned container. A naive "normalise the string" (NFKC, say)
 * would accept the last two, which v1 answers with a 500.
 *
 * The non-ASCII **space** half of the transform is already carried by {@link pythonIntStrip},
 * whose character set was measured for exactly this purpose (C63): folding a space to `' '`
 * and then skipping it at the edges is the same thing as stripping it, and a space that is not
 * at an edge fails the literal grammar either way.
 */
export function transformDecimalToAscii(value: string): string {
  // Fast path: `ch < 127` is CPython's own "leave it alone" test, and U+007F is not a digit,
  // so a string with no code point above U+007F is already its own transform.
  //
  // Written as a positive `[\u0080-\uffff]` range rather than a negated `[^\u0000-\u007f]`
  // one: the two are equivalent here -- every code point above U+007F, astral ones included,
  // is stored as at least one UTF-16 unit >= 0x80, and lone surrogates land in 0xD800-0xDFFF
  // -- but the negated form puts NUL inside the pattern and trips `no-control-regex`.
  if (!/[\u0080-\uffff]/.test(value)) {
    return value;
  }
  let out = '';
  for (const character of value) {
    const codePoint = character.codePointAt(0) as number;
    if (codePoint < 127) {
      out += character;
      continue;
    }
    const digit = pythonDecimalDigitValue(codePoint);
    out += digit < 0 ? character : String(digit);
  }
  return out;
}

/**
 * The literal grammar `PyLong_FromString` accepts for base 10, **including PEP 515**
 * underscores: an optional ASCII sign, then digits in which a single `_` may sit **between**
 * two digits and nowhere else.
 *
 * Measured in the pinned container:
 *
 * | input | CPython |
 * |---|---|
 * | `'1_0'` | `10` |
 * | `'1_0_0'` | `100` |
 * | `'+1_0'` / `'-1_0'` | `10` / `-10` |
 * | `' 1_0 '` | `10` — the strip happens around the literal |
 * | `'_1'`, `'1_'`, `'1__0'`, `'_'` | `ValueError` |
 * | `'1_ 0'`, `'1 _0'` | `ValueError` — the space is inside the literal |
 * | `'１_０'`, `'١_٠'`, `'1_٠'` | `10` — the fold runs first, so underscores mix with any script |
 */
const PYTHON_INT_LITERAL_RE = /^[+-]?[0-9](?:_?[0-9])*$/;

/**
 * CPython's `int(str)` for base 10, end to end: strip, fold, then match the literal grammar.
 * Returns `null` where CPython raises `ValueError`, so each caller can choose its own
 * exception type — `pythonInt` and `toDjangoInt` raise different classes for the same input.
 *
 * ⚠️ **Shared between `pythonInt` and `toDjangoInt` on purpose.** They had two copies of a
 * `/^[+-]?\d+$/` test, and JavaScript's `\d` is ASCII-only **with or without the `u` flag** —
 * so both refused `'１'` and `'1_0'`, which v1 accepts. On the query-string side that was a
 * v1 200 against a v2 500; on the **body** side `PUT {"value": "1_0"}` was a v1 **write of
 * 10** against a v2 500, on every integer field in Phases 3–6. One function, one grammar.
 *
 * Returns a `bigint` because CPython's `int` is unbounded and `toDjangoInt` feeds `bigint`
 * columns; `pythonInt` narrows.
 */
/**
 * The character class CPython's `\d` denotes **inside a `str` pattern with no `re.ASCII`** —
 * i.e. any decimal digit, not `[0-9]`. Built from the same pinned table the fold uses, so the
 * two can never disagree about what a digit is.
 */
const PYTHON_DIGIT_CLASS = ((): string => {
  let out = '';
  for (let i = 0; i < PYTHON_DECIMAL_DIGIT_RANGES.length; i += 2) {
    const lo = PYTHON_DECIMAL_DIGIT_RANGES[i];
    const hi = PYTHON_DECIMAL_DIGIT_RANGES[i + 1];
    const esc = (cp: number): string => `\\u{${cp.toString(16)}}`;
    out += lo === hi ? esc(lo) : `${esc(lo)}-${esc(hi)}`;
  }
  return out;
})();

/**
 * `datetime.strptime(value, '%Y-%m-%d')`, mirroring the pattern `_strptime` actually generates
 * rather than approximating it.
 *
 * ⚠️ **`strptime` is not one parser — it is a per-directive pattern, and the directives
 * disagree about Unicode.** "Does `strptime` accept Unicode digits?" is not a well-formed
 * question, which is exactly why measuring one string generalised wrongly. Dumped from the
 * pinned CPython 3.9.25:
 *
 * ```
 * _strptime.TimeRE().pattern('%Y-%m-%d')
 * '(?P<Y>\d\d\d\d)-(?P<m>1[0-2]|0[1-9]|[1-9])-(?P<d>3[0-1]|[1-2]\d|0[1-9]|[1-9]| [1-9])'
 * flags: IGNORECASE | UNICODE
 * ```
 *
 * * **`%Y` is `\d\d\d\d` — Unicode-aware**, and `int()` folds it. `'٢٠١٨-01-01'` is
 *   **2018-01-01**.
 * * **`%m` is ASCII in every branch.** `'2018-٠١-01'` is a `ValueError`.
 * * **`%d` is half.** The first character is ASCII in every branch, but `[1-2]\d`'s *second*
 *   character is Unicode-aware: `'2018-01-1٥'` is **2018-01-15**. And there is a
 *   **space-padded** branch `| [1-9]`, so `'2018-01- 5'` is **2018-01-05** — that one needs no
 *   exotic script at all, just a `%e`-style formatter on the client.
 *
 * All nine cases measured in the pinned container. An earlier version of this port refused all
 * of them and a register row recorded that refusal as *correct*, which is worse than the
 * original defect: a divergence a test asserts. Found by `nestjs-reviewer`.
 *
 * ⚠️ **The `$` anchor is not literally what `_strptime` does, and the equivalence is
 * format-specific.** CPython uses `re.match` plus a `found.end() != len(data_string)` check,
 * which does **not** backtrack for a longer overall match; JS `$` does. Worked through for
 * `%Y-%m-%d` and unobservable — the literal `-`s pin the month, and every `%d` branch is one
 * or two characters — but do not carry this shape to another format without redoing that
 * argument.
 *
 * Returns `null` where `strptime` raises, so each caller keeps its own exception text.
 */
const STRPTIME_ISO_RE = new RegExp(
  `^([${PYTHON_DIGIT_CLASS}]{4})-(1[0-2]|0[1-9]|[1-9])-(3[0-1]|[1-2][${PYTHON_DIGIT_CLASS}]|0[1-9]|[1-9]| [1-9])$`,
  'u',
);

export function parseStrptimeIsoDate(
  value: string,
): { year: number; month: number; day: number } | null {
  const match = STRPTIME_ISO_RE.exec(value);
  if (match === null) {
    return null;
  }
  // `int()` over the captured groups, which folds the Unicode digits `%Y` and `[1-2]\d` allow.
  // The space-padded day branch leaves a leading ' ', which `int()` strips.
  const year = Number(transformDecimalToAscii(match[1]));
  // The space-padded day branch leaves a leading ASCII space, which `int()` strips. `slice`
  // rather than `trim()`: this module documents at length that JS `trim()` is not Python's
  // whitespace set, and reaching for it here -- even where the regex makes it safe -- is how
  // that distinction erodes.
  const dayText = match[3].startsWith(' ') ? match[3].slice(1) : match[3];
  const day = Number(transformDecimalToAscii(dayText));
  // ⚠️ Defensive only, and deliberately NOT the countermeasure for UCD drift. The class and
  // the fold derive from the SAME `PYTHON_DECIMAL_DIGIT_RANGES` array, so they cannot disagree
  // about what a digit is -- verified exhaustively over all 1,114,112 code points, 0 in either
  // direction. This guard therefore covers a state the code makes unreachable; it is kept
  // because the alternative (a NaN year reaching a caller and being refused only by a
  // round-trip check) is a contract weaker than this helper's docblock claims. Drift is
  // controlled by the Major 5 matrix -- see Major 8.
  if (!Number.isFinite(year) || !Number.isFinite(day)) {
    return null;
  }
  return { year, month: Number(match[2]), day };
}

export function parsePythonIntLiteral(raw: string): bigint | null {
  const literal = transformDecimalToAscii(pythonIntStrip(raw));
  if (!PYTHON_INT_LITERAL_RE.test(literal)) {
    return null;
  }
  return BigInt(literal.replace(/_/g, ''));
}
export function pythonStr(value: unknown): string {
  return typeof value === 'string' ? value : pythonRepr(value);
}
