/**
 * CPython's `str()` and `repr()` for the shapes a parsed JSON body can carry.
 *
 * ## Why this module exists at all
 *
 * Django coerces on the way to the column: `CharField`/`TextField.get_prep_value` is
 * `to_python`, which is `str(value)` for anything that is not already a `str` or `None`.
 * Nothing in v1 validates a request body, so **whatever the client sent is what `str()` gets**
 * — including a list or a dict. Parity finding **P5-F1** was a v2 that stored the *type name*
 * (`'list'`, `'object'`) there, because {@link toDjangoText} reached for a helper whose own
 * docblock said it was "for an error message".
 *
 * The split this module enforces:
 *
 * | concern | function | may reach a column? |
 * |---|---|---|
 * | what CPython's `str()` renders | {@link pythonStr} | yes — used by `toDjangoText` |
 * | what CPython's `repr()` renders | {@link pythonRepr} | yes — `str()` of a container *is* its repr |
 * | naming a type inside a 500's message | `describeTypeForErrorMessage` (private to `python-obj.ts`) | **no** |
 *
 * ## Where the expected values come from
 *
 * `python-str.fixture.ts` is a **differential capture**, generated by
 * `scripts/gen-python-str-fixture.py` run inside the pinned v1 container
 * (CPython 3.9.25 / Django 2.2.27) against `TextField().get_prep_value(json.loads(body))`.
 * It is not a transcription of what anyone believes CPython does.
 *
 * ## Known limits, stated rather than hidden
 *
 * Three of them, all rooted in what `JSON.parse` throws away before this module is reached.
 * None is reachable from the fund's clients, and each would need a bespoke JSON scanner to
 * close (v2 already has one for error messages, `common/http/python-json.ts`, but it does not
 * build values):
 *
 *  1. **`int` vs `float`.** `json.loads('5.0')` is the float `5.0` and `str()` gives `'5.0'`;
 *     `JSON.parse('5.0')` is the number `5`, indistinguishable from `json.loads('5')`, and
 *     this module renders `'5'`. Only integral-valued floats are affected.
 *  2. **Very large integers.** `json.loads('10**21')` is a Python `int` rendering all 22
 *     digits; the same literal is a JS double rendering `'1e+21'`.
 *  3. **`dict` key order.** CPython preserves document order; a JS object reorders
 *     integer-like keys ahead of the rest, so `{"b":1,"1":2}` renders `{'1': 2, 'b': 1}` here
 *     and `{'b': 1, '1': 2}` in v1.
 */

/**
 * The complement of CPython's `str.isprintable()`:
 *
 * > Nonprintable characters are those characters defined in the Unicode character database as
 * > "Other" or "Separator", excepting the ASCII space.
 *
 * i.e. general categories `Cc Cf Cs Co Cn Zl Zp Zs`, minus U+0020. Verified against
 * `unicodedata.category` / `str.isprintable()` in the v1 container for the boundary code
 * points U+0085, U+00A0, U+00AD, U+0378, U+2000, U+2028, U+2029, U+200B, U+D7FF, U+FDD0,
 * U+E0001 (all non-printable) and U+1F600 (printable).
 */
const NON_PRINTABLE = /^[\p{Cc}\p{Cf}\p{Cs}\p{Co}\p{Cn}\p{Zl}\p{Zp}\p{Zs}]$/u;

/**
 * CPython's `unicode_escape`-style widths inside a `repr`:
 * `\xNN` below U+0100, `\uNNNN` below U+10000, `\UNNNNNNNN` above. Lowercase hex, as CPython
 * emits (`repr(U+200B ZERO WIDTH SPACE)` -> `"'\\u200b'"`, `repr('\U000e0001')` -> `"'\\U000e0001'"`).
 */
function escapeCodePoint(codePoint: number): string {
  if (codePoint < 0x100) {
    return `\\x${codePoint.toString(16).padStart(2, '0')}`;
  }
  if (codePoint < 0x10000) {
    return `\\u${codePoint.toString(16).padStart(4, '0')}`;
  }
  return `\\U${codePoint.toString(16).padStart(8, '0')}`;
}

/**
 * CPython's `unicode_repr` (`Objects/unicodeobject.c`).
 *
 * The quote rule is the one people get wrong: the default is `'`, and it switches to `"`
 * **only** when the string contains a `'` and no `"`. Measured:
 * `str(["a'b"])` -> `["a'b"]`, `str(['a"b'])` -> `['a"b']`, `str(["a'b\"c"])` -> `['a\'b"c']`.
 */
function reprString(value: string): string {
  const quote = value.includes("'") && !value.includes('"') ? '"' : "'";
  let out = quote;
  for (const character of value) {
    if (character === quote || character === '\\') {
      out += `\\${character}`;
    } else if (character === '\t') {
      out += '\\t';
    } else if (character === '\n') {
      out += '\\n';
    } else if (character === '\r') {
      out += '\\r';
    } else if (NON_PRINTABLE.test(character) && character !== ' ') {
      out += escapeCodePoint(character.codePointAt(0) as number);
    } else {
      out += character;
    }
  }
  return out + quote;
}

/**
 * `repr(float)` / `str(float)` — identical in Python 3.
 *
 * JavaScript and CPython already agree on the shortest round-tripping decimal form and on
 * `e+`/`e-` notation; they differ on the exponent's minimum width, which CPython pads to two
 * digits (`str(1e-7)` is `'1e-07'`, JS gives `'1e-7'`). `inf`/`-inf`/`nan` are CPython's
 * spellings; `JSON.parse` cannot produce them, but `json.loads` can, so they are covered.
 */
function reprNumber(value: number): string {
  if (Number.isNaN(value)) {
    return 'nan';
  }
  if (value === Infinity) {
    return 'inf';
  }
  if (value === -Infinity) {
    return '-inf';
  }
  return String(value).replace(/e([+-])(\d)$/, 'e$10$2');
}

/**
 * CPython's `repr()`.
 *
 * `str()` and `repr()` differ for exactly one of the JSON shapes — a `str`, where `str()` is
 * the identity and `repr()` quotes — so {@link pythonStr} is this function with that one case
 * short-circuited. A container's `str()` *is* its `repr()`, and it reprs its elements, which
 * is why `str({'a': 'b'})` is `{'a': 'b'}` and not `{a: b}`.
 */
export function pythonRepr(value: unknown): string {
  if (value === null || value === undefined) {
    return 'None';
  }
  if (typeof value === 'boolean') {
    return value ? 'True' : 'False';
  }
  if (typeof value === 'string') {
    return reprString(value);
  }
  if (typeof value === 'bigint') {
    return value.toString();
  }
  if (typeof value === 'number') {
    return reprNumber(value);
  }
  if (Array.isArray(value)) {
    return `[${value.map(pythonRepr).join(', ')}]`;
  }
  // `', '` between items and `': '` after a key — the spaces are part of the stored string.
  return `{${Object.entries(value as Record<string, unknown>)
    .map(([key, item]) => `${reprString(key)}: ${pythonRepr(item)}`)
    .join(', ')}}`;
}

/**
 * CPython's `str()`.
 *
 * This is what `'{}'.format(x)`, `'%s' % x` and `force_bytes(x)` produce, and therefore what
 * `refinance_loan`'s comment concatenation (`services/loan.py:141`) and
 * `set_password`'s hasher (`django.contrib.auth.hashers`) see. It is **not** the same
 * question as "what does Django store": a `None` is the four characters `None` here and SQL
 * `NULL` there. `toDjangoText` is the storage answer.
 */
/**
 * CPython's `str.strip()` with no argument - the character set is **not** JS `trim()`'s.
 *
 * `str.strip()` removes characters for which `str.isspace()` is true: Unicode category `Zs`
 * plus bidirectional class `WS`/`B`/`S`, which pulls in the C0 separators U+001C-U+001F and
 * U+0085 (NEL). `String.prototype.trim()` removes Unicode `White_Space` **plus U+FEFF**.
 *
 * Measured against the pinned container, they disagree in both directions:
 *
 * | codepoint | CPython `strip()` | JS `trim()` |
 * |---|---|---|
 * | U+001C-U+001F, U+0085 | strips | keeps |
 * | U+FEFF (BOM / ZWNBSP) | keeps | strips |
 *
 * So `trim()` is not a faithful port - it would trade one divergence for two smaller ones.
 * U+200B (ZERO WIDTH SPACE) is whitespace to neither and is stripped by neither.
 */
const PYTHON_SPACE =
  '\\t\\n\\v\\f\\r\\u001c-\\u001f \\u0085\\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000';
const PYTHON_STRIP_RE = new RegExp(`^[${PYTHON_SPACE}]+|[${PYTHON_SPACE}]+$`, 'gu');

export function pythonStrip(value: string): string {
  return value.replace(PYTHON_STRIP_RE, '');
}
export function pythonStr(value: unknown): string {
  return typeof value === 'string' ? value : pythonRepr(value);
}
