import {
  asPythonDict,
  pyGet,
  pyGetDict,
  pyHas,
  pythonInt,
  PythonKeyError,
  PythonTypeError,
  pythonGreaterThan,
  pythonNotEqual,
  toDjangoBool,
  toDjangoDate,
  toDjangoInt,
  toDjangoSmallInt,
  toDjangoText,
} from './python-obj';
import { DJANGO_TEXT_PREP_DIVERGENCES, DJANGO_TEXT_PREP_FIXTURE } from './python-str.fixture';
import { pythonStrip } from './python-str';

/**
 * The CPython behaviours v1's services rely on. Each cell states which v1 line depends on it,
 * because none of these is defensive programming — they decide whether a malformed request is
 * a 404, a 409 or a 500.
 *
 * Moved here from `src/users/` by review condition **C36**, together with the `pythonInt`
 * cases below, which were previously untested: Phases 4, 5 and 8 subscript `request.data` and
 * `int()` a query parameter exactly as Phase 3 does.
 */
describe('python-obj', () => {
  describe('asPythonDict', () => {
    it('accepts a mapping', () => {
      expect(asPythonDict({ a: 1 })).toEqual({ a: 1 });
    });

    it.each([[null], [[1, 2]], ['text'], [5], [true]])(
      'raises TypeError for %p, as `obj["type"]` does on a non-mapping',
      (value) => {
        expect(() => asPythonDict(value)).toThrow(PythonTypeError);
      },
    );
  });

  describe('pyGet / pyHas / pyGetDict', () => {
    it('raises KeyError with Python’s message shape', () => {
      expect(() => pyGet({}, 'type')).toThrow(PythonKeyError);
      expect(() => pyGet({}, 'type')).toThrow("KeyError: 'type'");
    });

    it('returns a present key even when its value is null or undefined', () => {
      expect(pyGet({ birthdate: null }, 'birthdate')).toBeNull();
      expect(pyHas({ birthdate: null }, 'birthdate')).toBe(true);
      expect(pyHas({}, 'birthdate')).toBe(false);
    });

    it('does not see inherited properties — `in` on a dict does not either', () => {
      expect(pyHas({}, 'toString')).toBe(false);
      expect(() => pyGet({}, 'toString')).toThrow(PythonKeyError);
    });

    it('pyGetDict raises KeyError for an absent section and TypeError for a scalar one', () => {
      expect(() => pyGetDict({}, 'personal')).toThrow(PythonKeyError);
      expect(() => pyGetDict({ personal: 5 }, 'personal')).toThrow(PythonTypeError);
    });
  });

  describe('toDjangoInt — `BigIntegerField.get_prep_value`', () => {
    it('accepts integers, bigints and decimal strings', () => {
      expect(toDjangoInt(123, 'x')).toBe(123n);
      expect(toDjangoInt(123n, 'x')).toBe(123n);
      expect(toDjangoInt('123', 'x')).toBe(123n);
      expect(toDjangoInt(' -45 ', 'x')).toBe(-45n);
      expect(toDjangoInt(12312451241243, 'x')).toBe(12312451241243n);
    });

    it('truncates a float, as CPython’s int() does', () => {
      expect(toDjangoInt(2.9, 'x')).toBe(2n);
      expect(toDjangoInt(-2.9, 'x')).toBe(-2n);
    });

    it('maps a boolean to 1/0 — `int(True)` is 1', () => {
      expect(toDjangoInt(true, 'x')).toBe(1n);
      expect(toDjangoInt(false, 'x')).toBe(0n);
    });

    it.each([['abc'], [''], [null], [{}], [[1]]])('raises for %p', (value) => {
      expect(() => toDjangoInt(value, 'identification')).toThrow(PythonTypeError);
    });

    it('toDjangoSmallInt narrows to a number for the role column', () => {
      expect(toDjangoSmallInt('2', 'role')).toBe(2);
    });
  });

  describe('toDjangoBool — `BooleanField.to_python`', () => {
    it.each([
      [true, true],
      [false, false],
      [1, true],
      [0, false],
      ['t', true],
      ['True', true],
      ['1', true],
      ['f', false],
      ['False', false],
      ['0', false],
    ])('maps %p to %p', (input, expected) => {
      expect(toDjangoBool(input, 'notifications')).toBe(expected);
    });

    it.each([['true'], ['yes'], [null], [2], [{}]])('raises for %p, as Django does', (value) => {
      expect(() => toDjangoBool(value, 'notifications')).toThrow(PythonTypeError);
    });
  });

  /**
   * **P5-F1 and D35 together.** `get_prep_value` is `to_python`, which is
   * `if isinstance(value, str) or value is None: return value` and otherwise `str(value)`.
   * Two consequences the old implementation got wrong, both measured on the pinned stack:
   *
   *  * `None` reaches the column as SQL **NULL** — it is never the four characters `'None'`
   *    (**D35**);
   *  * a `list`/`dict` reaches the column as CPython's **repr** — `['a']`, `{'a': 1}` — not
   *    as a type name (**P5-F1**).
   *
   * The table is not transcribed: it is the differential capture in
   * `python-str.fixture.ts`, generated by `scripts/gen-python-str-fixture.py` inside the v1
   * container, so a cell here cannot agree with a wrong belief about CPython.
   */
  describe('toDjangoText — `CharField`/`TextField.get_prep_value`', () => {
    it.each(DJANGO_TEXT_PREP_FIXTURE)('stores %s as the value Django stores', (body, expected) => {
      expect(toDjangoText(JSON.parse(body))).toBe(expected);
    });

    it('returns SQL NULL for None, not the string None (D35)', () => {
      expect(toDjangoText(null)).toBeNull();
      expect(toDjangoText(undefined)).toBeNull();
    });

    it('renders a container as CPython’s repr, not as a type name (P5-F1)', () => {
      expect(toDjangoText(['a'])).toBe("['a']");
      expect(toDjangoText({ a: 1 })).toBe("{'a': 1}");
      expect(toDjangoText([])).toBe('[]');
      expect(toDjangoText({})).toBe('{}');
      expect(toDjangoText({ a: [1, { b: 2 }] })).toBe("{'a': [1, {'b': 2}]}");
    });

    it('leaves the scalars alone — the positive control for the two cells above', () => {
      expect(toDjangoText(true)).toBe('True');
      expect(toDjangoText(false)).toBe('False');
      expect(toDjangoText(5)).toBe('5');
      expect(toDjangoText(5.5)).toBe('5.5');
      expect(toDjangoText('x')).toBe('x');
      expect(toDjangoText('')).toBe('');
    });

    /**
     * **C60 — the exponential threshold.** CPython switches to exponential iff
     * `decpt <= -4 || decpt > 16`; ECMA-262 iff `decpt <= -6 || decpt > 21`. The generated
     * fixture above now samples both boundaries from both sides, so these cells are the
     * *reason*, stated once, rather than a second copy of the data.
     */
    it('uses CPython’s exponential threshold, not JavaScript’s (C60)', () => {
      // Low boundary: JS would say '0.00001' / '0.000015'.
      expect(toDjangoText(0.00001)).toBe('1e-05');
      expect(toDjangoText(1.5e-5)).toBe('1.5e-05');
      expect(String(0.00001)).toBe('0.00001'); // the discriminator: what JS alone would store
      // High boundary: JS would say '10000000000000000'.
      expect(toDjangoText(1e16)).toBe('1e+16');
      expect(toDjangoText(1e17)).toBe('1e+17');
      expect(String(1e16)).toBe('10000000000000000');
      // Just inside the band on both sides — an off-by-one in either direction fails here.
      expect(toDjangoText(0.0001)).toBe('0.0001');
      expect(toDjangoText(4503599627370495.5)).toBe('4503599627370495.5');
      // The exponent is padded to two digits and no further.
      expect(toDjangoText(1e-7)).toBe('1e-07');
      expect(toDjangoText(1e-323)).toBe('1e-323');
    });

    /**
     * **C60 — the Unicode-database skew.** `\p{Cn}` answers with *Node's* UCD (17.0); v1's
     * `str.isprintable()` answers with CPython 3.9's (13.0). 15 933 code points disagreed.
     * The escape table is now captured from the container, so these cells pin the pinned
     * database rather than the local one — and they fail the moment someone reaches for the
     * regex again.
     */
    it('escapes by the pinned interpreter’s Unicode database, not Node’s (C60)', () => {
      const cn13 = /^[\p{Cc}\p{Cf}\p{Cs}\p{Co}\p{Cn}\p{Zl}\p{Zp}\p{Zs}]$/u;
      // Assigned in UCD 14-17, unassigned in 13.0 — v1 escapes all three.
      expect(toDjangoText(['\u0870'])).toBe("['\\u0870']");
      expect(toDjangoText(['\u{1e7e0}'])).toBe("['\\U0001e7e0']");
      expect(toDjangoText(['\u{13e8f}'])).toBe("['\\U00013e8f']");
      // Node disagrees about every one of them — this is the discriminator.
      expect(cn13.test('\u0870')).toBe(false);
      expect(cn13.test('\u{1e7e0}')).toBe(false);
      // Controls, both measured in the container: U+11FB0 and U+1F600 were already assigned
      // in UCD 13 and are stored literally by both stacks; U+0378 is unassigned in both and
      // is escaped by both. Without these the cell above could pass by escaping everything.
      expect(toDjangoText(['\u{11fb0}'])).toBe("['\u{11fb0}']");
      expect(toDjangoText(['\u{1f600}'])).toBe("['\u{1f600}']");
      expect(toDjangoText(['\u0378'])).toBe("['\\u0378']");
    });

    /**
     * **The "Known limits" block, as cells.** Each body below is one CPython behaviour v2
     * deliberately does not reproduce, because `JSON.parse` has already discarded what it
     * would need. v1's value is generated in the container; v2's is written here. A limit
     * that is silently closed fails the first `expect`; one that widens fails the second.
     */
    describe('known limits — pinned in both directions', () => {
      const v2Renders: Record<string, string> = {
        '5.0': '5',
        '-2.0': '-2',
        '1e-330': '0',
        '-0.0': '0',
        '10000000000000000': '1e+16',
        '9999999999999999': '1e+16',
        '1000000000000000000000': '1e+21',
        '{"b": 1, "1": 2}': "{'1': 2, 'b': 1}",
        '{"10": 0, "9": 1}': "{'9': 1, '10': 0}",
      };

      it.each(DJANGO_TEXT_PREP_DIVERGENCES)(
        'v1 stores %s as %j — v2 does not, and that is limit 1 or 2',
        (body, v1Value) => {
          const rendered = toDjangoText(JSON.parse(body));
          expect(rendered).toBe(v2Renders[body]);
          expect(rendered).not.toBe(v1Value);
        },
      );

      it('covers every divergent body the generator emits', () => {
        expect(DJANGO_TEXT_PREP_DIVERGENCES.map(([body]) => body).sort()).toEqual(
          Object.keys(v2Renders).sort(),
        );
      });
    });
  });

  describe('pythonNotEqual — `__update_user_finance`’s change check', () => {
    it('is False for an equal integer, whatever its JavaScript type', () => {
      expect(pythonNotEqual(2000n, 2000)).toBe(false);
      expect(pythonNotEqual(2000n, 2000n)).toBe(false);
    });

    it('is True for a stringified number — Python’s `2000 != "2000"` is True', () => {
      // ⚠️ Deliberately different from `changedFields`, which normalises. This one decides
      // whether v1 would have written the row and bumped `last_modified`.
      expect(pythonNotEqual(2000n, '2000')).toBe(true);
    });

    it('is True for a float that is not the same integer', () => {
      expect(pythonNotEqual(2000n, 2000.5)).toBe(true);
    });

    it('compares booleans by identity, so a stored False differs from "false"', () => {
      expect(pythonNotEqual(false, false)).toBe(false);
      expect(pythonNotEqual(false, 'false')).toBe(true);
      expect(pythonNotEqual(true, false)).toBe(true);
    });

    it('is True for null and for objects', () => {
      expect(pythonNotEqual(1n, null)).toBe(true);
      expect(pythonNotEqual(1n, {})).toBe(true);
    });
  });

  describe('pythonGreaterThan — `create_loan`’s quota gate (`services/loan.py:27`)', () => {
    /**
     * Every expectation in this block was run through CPython before it was written here:
     *
     * ```
     * >>> 1000.5 > 1000, 999.5 > 1000, 1000.0 > 1000
     * (True, False, False)
     * >>> True > 0, True > 1, False > 0, False > -1
     * (True, False, False, True)
     * >>> 9007199254740992.0 > 9007199254740993
     * False
     * ```
     */
    it('is False at the boundary — the check is `>`, not `>=`', () => {
      expect(pythonGreaterThan(500, 500n)).toBe(false);
      expect(pythonGreaterThan(500n, 500n)).toBe(false);
      expect(pythonGreaterThan(501, 500n)).toBe(true);
      expect(pythonGreaterThan(499, 500n)).toBe(false);
    });

    /**
     * ⚠️ **D29's divergent window, and the whole reason this helper exists.** A fractional
     * value strictly between the quota and the quota + 1 is *greater* raw — v1's 406 — and
     * *equal* once `toDjangoInt` has truncated it, which is the 201 v2 used to answer while
     * storing a number the member never submitted.
     */
    it('is True for a fraction inside `(quota, quota + 1)`, where truncation says equal', () => {
      expect(pythonGreaterThan(500.5, 500n)).toBe(true);
      expect(toDjangoInt(500.5, 'value')).toBe(500n); // …and this is why ordering matters
      expect(pythonGreaterThan(500.000001, 500n)).toBe(true);
    });

    it('is False for a fraction below the quota — both stacks accept and both store the floor', () => {
      expect(pythonGreaterThan(499.5, 500n)).toBe(false);
      expect(pythonGreaterThan(-0.5, -1n)).toBe(true);
    });

    it('treats a bool as an int, as Python’s subclassing does', () => {
      expect(pythonGreaterThan(true, 0n)).toBe(true);
      expect(pythonGreaterThan(true, 1n)).toBe(false);
      expect(pythonGreaterThan(false, 0n)).toBe(false);
      expect(pythonGreaterThan(false, -1n)).toBe(true);
    });

    /** CPython compares an `int` and a `float` **exactly**; it never rounds the int. */
    it('compares exactly beyond 2^53, where a double round-trip would lie', () => {
      expect(pythonGreaterThan(9_007_199_254_740_992, 9_007_199_254_740_993n)).toBe(false);
      expect(pythonGreaterThan(9_007_199_254_740_994, 9_007_199_254_740_993n)).toBe(true);
    });

    it('is False for NaN — every comparison with nan is False in Python', () => {
      expect(pythonGreaterThan(Number.NaN, 0n)).toBe(false);
      expect(pythonGreaterThan(Number.POSITIVE_INFINITY, 0n)).toBe(true);
      expect(pythonGreaterThan(Number.NEGATIVE_INFINITY, 0n)).toBe(false);
    });

    /**
     * ⚠️ The helper stays faithful to CPython here. **D29's leniency for a string lives at
     * `createLoan`'s call site**, which coerces before comparing — deliberately, so the
     * deviation is visible where it is taken rather than hidden in a shared helper Phases 5–8
     * will reuse.
     */
    it.each([
      ['1000', "'>' not supported between instances of 'str' and 'int'"],
      [null, "'>' not supported between instances of 'NoneType' and 'int'"],
      [{}, "'>' not supported between instances of 'dict' and 'int'"],
      [[], "'>' not supported between instances of 'list' and 'int'"],
    ])('raises CPython’s TypeError for %p, which v1 never catches', (value, message) => {
      expect(() => pythonGreaterThan(value, 1n)).toThrow(PythonTypeError);
      expect(() => pythonGreaterThan(value, 1n)).toThrow(message);
    });
  });

  describe('toDjangoDate — `DateField.to_python` / `dateparse.parse_date`', () => {
    it('accepts a zero-padded date', () => {
      expect(toDjangoDate('2018-01-01', 'd')).toEqual({ year: 2018, month: 1, day: 1 });
    });

    /**
     * ⚠️ The regex is `\d{1,2}` for month and day, and v1's own loan fixtures rely on it:
     * `test_loan_views.py:64` posts `'2017-12-9'` and `:110` posts `'2018-1-1'`. A
     * `YYYY-MM-DD`-only implementation refuses bodies v1 accepts and writes.
     */
    it('accepts an UNPADDED month and day, as Django’s date_re does', () => {
      expect(toDjangoDate('2017-12-9', 'd')).toEqual({ year: 2017, month: 12, day: 9 });
      expect(toDjangoDate('2018-1-1', 'd')).toEqual({ year: 2018, month: 1, day: 1 });
      expect(toDjangoDate('2018-1-15', 'd')).toEqual({ year: 2018, month: 1, day: 15 });
    });

    it('accepts one trailing newline, because Python’s `$` matches before it', () => {
      expect(toDjangoDate('2018-01-01\n', 'd')).toEqual({ year: 2018, month: 1, day: 1 });
    });

    it('rejects two trailing newlines — `$` allows exactly one', () => {
      expect(() => toDjangoDate('2018-01-01\n\n', 'd')).toThrow(/invalid date format/);
    });

    it.each([
      '',
      '18-01-01',
      '2018/01/01',
      '01-01-2018',
      '2018-01-01T00:00:00',
      ' 2018-01-01',
      'abc',
    ])('rejects %p with a ValidationError', (value) => {
      expect(() => toDjangoDate(value, 'd')).toThrow(/invalid date format/);
    });

    it('rejects an out-of-range date after the regex matches — Django’s invalid_date branch', () => {
      expect(() => toDjangoDate('2018-13-01', 'd')).toThrow(/invalid date/);
      expect(() => toDjangoDate('2018-02-30', 'd')).toThrow(/invalid date/);
      expect(() => toDjangoDate('2019-02-29', 'd')).toThrow(/invalid date/);
      expect(() => toDjangoDate('2018-00-01', 'd')).toThrow(/invalid date/);
      expect(() => toDjangoDate('2018-01-00', 'd')).toThrow(/invalid date/);
    });

    it('accepts 29 February in a leap year, including the century rule', () => {
      expect(toDjangoDate('2020-02-29', 'd')).toEqual({ year: 2020, month: 2, day: 29 });
      expect(toDjangoDate('2000-02-29', 'd')).toEqual({ year: 2000, month: 2, day: 29 });
      expect(() => toDjangoDate('2100-02-29', 'd')).toThrow(/invalid date/);
    });

    it('a non-string is a TypeError from `re.match`, which to_python does NOT catch', () => {
      expect(() => toDjangoDate(20180101, 'd')).toThrow(/TypeError/);
      expect(() => toDjangoDate(null, 'd')).toThrow(/TypeError/);
      expect(() => toDjangoDate({ year: 2018 }, 'd')).toThrow(/TypeError/);
    });

    it('names the field in the message, so a 500 log says which column failed', () => {
      expect(() => toDjangoDate('nope', 'disbursement_date')).toThrow(/disbursement_date/);
    });
  });

  describe('pythonInt — CPython `int(str)`', () => {
    it('parses a plain decimal', () => {
      expect(pythonInt('12')).toBe(12);
    });

    it('allows surrounding whitespace and a sign, as int() does', () => {
      expect(pythonInt('  7  ')).toBe(7);
      expect(pythonInt('+7')).toBe(7);
      expect(pythonInt('-7')).toBe(-7);
    });

    it('raises ValueError for an empty string — `?page=` is a 500, not a 400', () => {
      expect(() => pythonInt('')).toThrow("ValueError: invalid literal for int() with base 10: ''");
    });

    it('raises ValueError for a non-integer, quoting the RAW value in the message', () => {
      expect(() => pythonInt('abc')).toThrow(
        "ValueError: invalid literal for int() with base 10: 'abc'",
      );
      // Not the trimmed one: CPython echoes what it was given.
      expect(() => pythonInt(' 1.5 ')).toThrow(
        "ValueError: invalid literal for int() with base 10: ' 1.5 '",
      );
    });

    it('refuses a float, a hex literal and an underscored literal', () => {
      for (const raw of ['1.0', '0x10', '1e3']) {
        expect(() => pythonInt(raw)).toThrow('ValueError');
      }
    });

    /**
     * **C63 — `int()`'s whitespace set is a third answer**, neither `trim()`'s nor
     * `pythonStrip`'s. Both call sites used `trim()`, which is the mistake `pythonStrip` was
     * written to close, in the same directory. Every expectation below was measured in the
     * pinned container as `int(ch + '5' + ch)`; the paired `trim()` assertion is the
     * discriminator, so reverting to `trim()` fails these cells rather than passing them.
     *
     * Reachable from `?page=` on `GET /api/user` and `GET /api/loan` (P4-D4's unguarded
     * `int()`), and from `value` / `identification` / `state` in a body.
     */
    it('skips U+0085 (NEL), which JS trim() keeps — v1 answers where v2 used to 500', () => {
      expect(pythonInt('\u00855\u0085')).toBe(5);
      expect(toDjangoInt('\u00855\u0085', 'value')).toBe(5n);
      expect(() => {
        const trimmed = '\u00855\u0085'.trim();
        if (!/^[+-]?\d+$/.test(trimmed)) throw new Error('ValueError');
      }).toThrow('ValueError');
    });

    /**
     * The case that justifies `pythonIntStrip` existing separately from `pythonStrip`: these
     * two disagree with **each other**, not merely with JS `trim()`.
     *
     * Measured in the container: `int('\u001c5\u001c')` raises `ValueError`, while
     * `'\u001c5\u001c'.strip()` returns `'5'`. So `int()`'s whitespace set is not
     * `str.strip()`'s, and routing integers through the string helper would make v2 answer
     * where v1 raises.
     */
    it('refuses U+001C, which str.strip() strips — int() and strip() are different sets', () => {
      expect(() => pythonInt('\u001c5\u001c')).toThrow('ValueError');
      expect(() => toDjangoInt('\u001c5\u001c', 'value')).toThrow('ValueError');
      // The discriminator: the *string* helper does strip it, which is why they are two.
      expect(pythonStrip('\u001c5\u001c')).toBe('5');
    });

    it('refuses U+FEFF (BOM), which JS trim() strips — v1 500s where v2 used to answer', () => {
      expect(() => pythonInt('\ufeff5')).toThrow('ValueError');
      expect(() => toDjangoInt('\ufeff5', 'value')).toThrow(PythonTypeError);
      expect('\ufeff5'.trim()).toBe('5');
    });

    it('refuses U+001C-U+001F, which `str.strip()` DOES strip — so `pythonStrip` is the wrong helper', () => {
      for (const ch of ['\u001c', '\u001d', '\u001e', '\u001f']) {
        expect(() => pythonInt(ch + '5')).toThrow('ValueError');
        expect(() => toDjangoInt(ch + '5', 'value')).toThrow(PythonTypeError);
      }
      expect(pythonStrip('\u001c5\u001f')).toBe('5');
    });

    it('skips the Unicode separators int() accepts, and refuses the two it does not', () => {
      for (const ch of [
        '\u00a0',
        '\u1680',
        '\u2000',
        '\u200a',
        '\u2028',
        '\u2029',
        '\u202f',
        '\u205f',
        '\u3000',
      ]) {
        expect(pythonInt(ch + '5' + ch)).toBe(5);
      }
      for (const ch of ['\u200b', '\u180e']) {
        expect(() => pythonInt(ch + '5')).toThrow('ValueError');
      }
    });
  });

  /**
   * ## B1 - `int()`'s digit set and PEP 515, neither of which C63 closed
   *
   * Every expectation here was measured on the pinned interpreter (CPython 3.9.25), not
   * reasoned about. The defect these close was live through a review, a phase and a parity
   * round because the docblock claimed `pythonInt` "reproduces CPython's `int()`" when C63 had
   * closed the whitespace axis ONLY -- false-green #20's family, turned inward. The whitespace
   * cells live above under C63; these are the two axes nobody had checked.
   *
   * WARNING: `pythonInt` and `toDjangoInt` are asserted TOGETHER on every row. They had two
   * copies of the same regex, and the copies are what let the write side diverge unnoticed:
   * `pythonInt` guards query strings (a v1 200 against a v2 500) but `toDjangoInt` guards
   * request bodies, so `PUT {"value": "1_0"}` was a v1 WRITE OF 10 against a v2 500, on every
   * integer body field in Phases 3-6. One grammar, two callers, one set of cells.
   */
  describe('B1 - non-ASCII decimal digits and PEP 515 underscores', () => {
    const accepted: ReadonlyArray<readonly [string, number, string]> = [
      ['１', 1, 'U+FF11 FULLWIDTH DIGIT ONE - Nd, folded'],
      ['١', 1, 'U+0661 ARABIC-INDIC DIGIT ONE'],
      ['۱', 1, 'U+06F1 EXTENDED ARABIC-INDIC DIGIT ONE'],
      ['１２３', 123, 'folded digit by digit'],
      ['1１', 11, 'mixed scripts - CPython has no "same script" rule'],
      ['1_0', 10, 'PEP 515'],
      ['1_0_0', 100, 'PEP 515, repeated'],
      ['+1_0', 10, 'sign then underscore'],
      ['-1_0', -10, 'negative'],
      [' 1_0 ', 10, 'the strip happens around the literal'],
      ['１_０', 10, 'the fold runs first, so underscores mix with any script'],
    ];

    it.each(accepted)('int(%j) === %i  // %s', (raw, expected) => {
      expect(pythonInt(raw)).toBe(expected);
      expect(toDjangoInt(raw, 'f')).toBe(BigInt(expected));
    });

    // The refusals are the half a naive fix breaks. "Normalise the string" (NFKC, say) would
    // accept the fullwidth SIGNS, which v1 answers with a 500 -- so a mutant that over-folds
    // is caught here rather than in production.
    const refused: ReadonlyArray<readonly [string, string]> = [
      ['＋1', 'U+FF0B FULLWIDTH PLUS - Sm, NOT folded; the sign must be ASCII'],
      ['－1', 'U+FF0D FULLWIDTH HYPHEN-MINUS - Pd, NOT folded'],
      ['_1', 'leading underscore'],
      ['1_', 'trailing underscore'],
      ['1__0', 'doubled underscore'],
      ['_', 'bare underscore'],
      ['1_ 0', 'space inside the literal'],
      ['1 _0', 'space inside the literal'],
    ];

    it.each(refused)('int(%j) raises  // %s', (raw) => {
      expect(() => pythonInt(raw)).toThrow(/invalid literal for int\(\) with base 10/);
      expect(() => toDjangoInt(raw, 'f')).toThrow(PythonTypeError);
    });

    /**
     * The reason this is a captured table and not a Unicode-property regex. CPython 3.9.25 is
     * on UCD 13.0.0; Node 24 is on UCD 17.0, so Node's Nd property accepts ~120 code points v1
     * refuses -- every digit block assigned since 2020 -- turning a v1 ValueError (a 500) into
     * a v2 success. These are Nd to Node and unknown to the pinned interpreter: they MUST raise.
     */
    it.each([
      ['\u{11F50}', 'U+11F50 KAWI DIGIT ZERO - Nd since UCD 15.0'],
      ['\u{1E4F0}', 'U+1E4F0 NAG MUNDARI DIGIT ZERO - UCD 15.0'],
      ['\u{116D0}', 'U+116D0 MYANMAR PAO DIGIT ZERO - UCD 16.0'],
    ])('refuses %j, added to Nd after UCD 13.0  // %s', (raw) => {
      expect(() => pythonInt(raw)).toThrow(/invalid literal for int\(\) with base 10/);
      // ⚠️ The write side too, per this block's own rule -- `nestjs-reviewer` caught that
      // these three cells asserted `pythonInt` only. A `\p{Nd}` regression would have let
      // `PUT {"value": "<post-UCD-13 digit>"}` WRITE where v1 answers 500, and no cell would
      // have seen it. This is the direction that matters most, and it took the control from
      // 3 failures to 6.
      expect(() => toDjangoInt(raw, 'f')).toThrow(PythonTypeError);
    });
  });

  /**
   * ## B2 - `toDjangoDate` never validated the year
   *
   * Found by `nestjs-reviewer` after `manual-tester` found the sibling value bug. Django's
   * `parse_date` regex takes four digits, so '0000-01-01' matches and reaches
   * `datetime.date(0, 1, 1)`, which raises `ValueError: year must be in 1..9999, not 0`;
   * `DateField.to_python` turns that into `ValidationError('invalid_date')`.
   *
   * WARNING: this one is a STATUS divergence on a write path, not a value divergence. v2
   * answered 200 and wrote a row dated 1900-01-01 where v1 answers 500 and writes nothing --
   * it creates a row v1 would never have created, on every date-taking write in Phases 3-6.
   */
  describe('B2 - toDjangoDate year range', () => {
    it('refuses year 0000, which JS Date.UTC would have mapped to 1900', () => {
      expect(() => toDjangoDate('0000-01-01', 'end_date')).toThrow(PythonTypeError);
      expect(() => toDjangoDate('0000-12-31', 'end_date')).toThrow(
        /correct format \(YYYY-MM-DD\) but it is an invalid date/,
      );
    });

    it('accepts the boundary years datetime.date accepts', () => {
      expect(toDjangoDate('0001-01-01', 'end_date')).toEqual({ year: 1, month: 1, day: 1 });
      expect(toDjangoDate('9999-12-31', 'end_date')).toEqual({ year: 9999, month: 12, day: 31 });
      // Inside the Date.UTC remap window, and a real date to datetime.date.
      expect(toDjangoDate('0050-06-15', 'end_date')).toEqual({ year: 50, month: 6, day: 15 });
    });

    it('leap-year arithmetic is not confused by the remap window', () => {
      // Year 4 is a leap year and so is 1904, so this cell alone would NOT catch a raw
      // Date.UTC inside daysInMonth -- it documents that rather than disproving it. The
      // reviewer's proof is the real guarantee: for y in [1,99], (y+1900)%4 === y%4 and
      // y%100 !== 0, so the answers coincide for every year the range check now admits.
      expect(toDjangoDate('0004-02-29', 'end_date')).toEqual({ year: 4, month: 2, day: 29 });
      expect(() => toDjangoDate('0100-02-29', 'end_date')).toThrow(PythonTypeError);
    });

    /**
     * ## D42, fourth axis — Django's `date_re` is Unicode-aware and JS `\d` is not
     *
     * Same root cause as B1, one function over: `dateparse.date_re` is compiled from a `str`
     * pattern with no `re.ASCII`, so its `\d` matches any `Nd` code point, and `parse_date`
     * then runs `int()` over the groups -- which folds them. Measured on the pinned CPython
     * 3.9.25:
     *     date_re.match('٢٠١٨-٠١-٠١').groupdict() -> {'year': '٢٠١٨', ...} -> date(2018, 1, 1)
     *
     * ⚠️ **It does NOT stop here, and an earlier version of this docblock said it did.**
     * `_strptime` generates a per-directive pattern and the directives disagree: `%Y` is
     * `\d\d\d\d` and Unicode-aware, `%m` is ASCII in every branch, and `%d` is
     * **per branch**: `0[1-9]` and `3[0-1]` are ASCII in BOTH characters, only `[1-2]\d`'s
     * second character is Unicode-aware, and there is a space-padded ` [1-9]` branch.
     * ⚠️ This sentence used to read *"ASCII in its first character only"* — which is exactly
     * the over-reading a counter-mutant proved passes all 2319 tests while turning
     * `'2018-01-0٥'` into a 200-with-a-row where v1 raises. Prose arguing for a rule the code
     * contradicts, with no cell able to arbitrate; `loan.service.spec.ts` now has the two
     * refusing rows that arbitrate it. `strptime('٢٠١٨-٠١-٠١')` fails **because of the month** -- one
     * measurement of one string, generalised into a rule that was wrong for seven other
     * inputs. See {@link parseStrptimeIsoDate} and `loan.service.spec.ts`'s Major 5 matrix.
     */
    it('D42: folds Unicode decimal digits, because Django date_re + int() does', () => {
      expect(toDjangoDate('٢٠١٨-٠١-٠١', 'end_date')).toEqual({ year: 2018, month: 1, day: 1 });
      expect(toDjangoDate('２０１８-01-01', 'end_date')).toEqual({ year: 2018, month: 1, day: 1 });
    });

    it('D42: still refuses a post-UCD-13.0 digit here too', () => {
      // The fold uses the pinned interpreter's table, so the drift guard holds on this path
      // as well -- v1's `int()` would raise, so the row must not be written.
      expect(() => toDjangoDate('\u{1E4F0}018-01-01', 'end_date')).toThrow(PythonTypeError);
    });
  });
});
